import {browserOptions} from './browser-options.mjs';
import {chromium} from 'playwright';import assert from 'node:assert/strict';import path from 'node:path';import fs from 'node:fs';import {serve} from './serve.mjs?v=2a52c2515340ef0d';import {observeBrowser} from './observe.mjs?v=f04a42ac0648481b';
const root=path.resolve(import.meta.dirname,'../..'),server=await serve(root),report={profiles:[],retry:null};
const browser=await chromium.launch(browserOptions());
async function shell(page){await page.goto(server.url+'?qa=1');await page.waitForFunction(()=>globalThis.__chevyV6Complete?.menuReady);await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelector('#an-intro')?.hidden!==false);}
try{
 for(const entry of [{id:'new',raw:null},{id:'existing',raw:JSON.stringify({version:6,workshopTokens:345,journey:{km:8,routes:[]}})},{id:'old',raw:JSON.stringify({version:3,workshopTokens:217,unlocked:{old:true},journey:{km:2}})},{id:'corrupt',raw:'{broken'},{id:'quota',raw:JSON.stringify({workshopTokens:178}),quota:true}]){
  const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(observeBrowser);await page.addInitScript(({raw,quota})=>{if(raw!==null)localStorage.setItem('chevy-serie2-v6-profile',raw);if(quota){const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='chevy-serie2-v6-profile')throw new DOMException('Injected quota','QuotaExceededError');return set.call(this,k,v);};}},entry);await shell(page);await page.locator('[data-v6-panel="drive"]').click();const data=await page.evaluate(()=>({profile:__chevyV6Complete.profile(),raw:localStorage.getItem('chevy-serie2-v6-profile'),audit:__noFreezeAudit.snapshot()}));assert.equal(data.profile.workshopTokens,entry.id==='new'||entry.id==='corrupt'?100:JSON.parse(entry.raw).workshopTokens);if(entry.id==='corrupt')assert.equal(data.raw,entry.raw);assert.deepEqual(errors,[]);assert.deepEqual(data.audit.errors,[]);assert.equal(data.audit.gl.length,0);report.profiles.push({id:entry.id,passed:true});await context.close();
 }
 const context=await browser.newContext(),page=await context.newPage(),requests=[],errors=[];await page.addInitScript(observeBrowser);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.route('**/assets/manifests/workshop-bootstrap.json*',r=>r.fulfill({status:503,body:'Intentional test failure'}));await shell(page);await page.locator('[data-v6-panel="workshop"]').click();await page.waitForFunction(()=>__chevyV6Complete.workshop.failed);assert(!requests.some(u=>/cockpit-payload|source-parts|workshop.*\.glb/.test(u)),'Failed bootstrap triggered heavy recovery');await page.unroute('**/assets/manifests/workshop-bootstrap.json*');await page.getByRole('button',{name:'Reintentar',exact:true}).click();await page.waitForFunction(()=>__chevyV6Complete.workshop.loaded,null,{timeout:180000});assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>__asfaltoEngineBootstrap.diagnostics().phase),'ready');report.retry={passed:true,heavyFallback:false};await context.close();
}finally{fs.mkdirSync(path.join(root,'test-results/no-freeze'),{recursive:true});fs.writeFileSync(path.join(root,'test-results/no-freeze/fault-flows.json'),JSON.stringify(report,null,2));await browser.close();await server.close();}console.log(JSON.stringify(report));
