// Browser-side observers used by the audit harness; no production behavior changed.
export function observeBrowser(){
 const now=()=>performance.now();const state={phase:'navigation',longTasks:[],errors:[],contextLosses:[],rafOwners:[],gl:[],audio:[],workerEvents:[],timers:{timeouts:0,intervals:0},frames:[]};
 const raw={raf:requestAnimationFrame.bind(window),cancel:cancelAnimationFrame.bind(window),timeout:setTimeout.bind(window),clearTimeout:clearTimeout.bind(window),interval:setInterval.bind(window),clearInterval:clearInterval.bind(window)};
 const pending=new Map(),owners=new WeakMap();let lastFrame=-1;
 window.requestAnimationFrame=fn=>{let owner=owners.get(fn);if(!owner){owner={id:state.rafOwners.length,name:fn.name||'anonymous',stack:state.rafOwners.length<160?String(new Error().stack).slice(0,1200):'',calls:0,ms:0,maxMs:0,pending:0};owners.set(fn,owner);if(state.rafOwners.length<200)state.rafOwners.push(owner);}let id;id=raw.raf(ts=>{pending.delete(id);owner.pending--;if(ts!==lastFrame){if(lastFrame>=0&&state.frames.length<120000)state.frames.push({at:ts,dt:ts-lastFrame,phase:state.phase});lastFrame=ts;}const start=now();try{return fn(ts);}finally{const ms=now()-start;owner.calls++;owner.ms+=ms;owner.maxMs=Math.max(owner.maxMs,ms);}});pending.set(id,owner);owner.pending++;return id;};
 window.cancelAnimationFrame=id=>{const owner=pending.get(id);if(owner){owner.pending--;pending.delete(id);}return raw.cancel(id);};
 const timeouts=new Set(),intervals=new Set();window.setTimeout=(fn,ms,...args)=>{let id;id=raw.timeout(typeof fn==='function'?()=>{timeouts.delete(id);return fn(...args);}:fn,ms,...(typeof fn==='function'?[]:args));timeouts.add(id);return id;};window.clearTimeout=id=>{timeouts.delete(id);return raw.clearTimeout(id);};window.setInterval=(fn,ms,...args)=>{const id=raw.interval(fn,ms,...args);intervals.add(id);return id;};window.clearInterval=id=>{intervals.delete(id);return raw.clearInterval(id);};
 const nativeAdd=EventTarget.prototype.addEventListener;
 nativeAdd.call(window,'unhandledrejection',e=>state.errors.push({type:'unhandledrejection',phase:state.phase,message:String(e.reason?.stack||e.reason)}));
 try{new PerformanceObserver(list=>{for(const entry of list.getEntries())if(state.longTasks.length<10000)state.longTasks.push({start:entry.startTime,ms:entry.duration,phase:state.phase});}).observe({entryTypes:['longtask']});}catch{}
 const contexts=new WeakMap();const get=HTMLCanvasElement.prototype.getContext;
 HTMLCanvasElement.prototype.getContext=function(type,...args){const gl=get.call(this,type,...args);if(gl&&/^webgl/.test(type)&&!contexts.has(gl)){
  const info={id:state.gl.length,type,phase:state.phase,createdAt:now(),lost:false,disposedByRequest:false,resources:{}};contexts.set(gl,info);state.gl.push(info);
  nativeAdd.call(this,'webglcontextlost',()=>{info.lost=true;state.contextLosses.push({at:now(),phase:state.phase,id:info.id,requested:info.disposedByRequest});});nativeAdd.call(this,'webglcontextrestored',()=>info.lost=false);
  for(const suffix of ['Texture','Buffer','Framebuffer','Renderbuffer','Program','Shader','VertexArray','Query']){const create='create'+suffix,del='delete'+suffix;if(typeof gl[create]!=='function')continue;const objects=new WeakSet(),counts=info.resources[suffix]={created:0,deleted:0,live:0};const make=gl[create].bind(gl),remove=gl[del]?.bind(gl);gl[create]=(...a)=>{const object=make(...a);if(object){objects.add(object);counts.created++;counts.live++;}return object;};if(remove)gl[del]=object=>{if(object&&objects.has(object)){objects.delete(object);counts.deleted++;counts.live--;}return remove(object);};}
  const extension=gl.getExtension.bind(gl);gl.getExtension=name=>{const ext=extension(name);if(name==='WEBGL_lose_context'&&ext&&!ext.__auditWrapped){const lose=ext.loseContext.bind(ext);ext.loseContext=()=>{info.disposedByRequest=true;return lose();};ext.__auditWrapped=true;}return ext;};
 }return gl;};
 if(window.Worker){const Native=window.Worker;window.Worker=new Proxy(Native,{construct(target,args){const worker=Reflect.construct(target,args),id=state.workerEvents.length;state.workerEvents.push({type:'create',id,url:String(args[0]),at:now(),phase:state.phase});const stop=worker.terminate.bind(worker);worker.terminate=()=>{state.workerEvents.push({type:'terminate',id,at:now(),phase:state.phase});return stop();};return worker;}});}
 for(const key of ['AudioContext','webkitAudioContext']){const Native=window[key];if(!Native)continue;window[key]=new Proxy(Native,{construct(target,args){const audio=Reflect.construct(target,args),info={id:state.audio.length,state:audio.state,phase:state.phase,createdAt:now()};state.audio.push(info);nativeAdd.call(audio,'statechange',()=>info.state=audio.state);return audio;}});}
 window.__noFreezeAudit={state,mark:phase=>{state.phase=phase;performance.mark('no-freeze:'+phase);},snapshot:()=>({phase:state.phase,pendingRaf:pending.size,rafOwners:state.rafOwners.map(o=>({...o})),timers:{timeouts:timeouts.size,intervals:intervals.size},gl:structuredClone(state.gl),audio:structuredClone(state.audio),workerEvents:structuredClone(state.workerEvents),longTasks:state.longTasks.slice(),errors:state.errors.slice(),contextLosses:state.contextLosses.slice(),frames:state.frames.slice(),navigation:performance.getEntriesByType('navigation').map(e=>e.toJSON()),paint:performance.getEntriesByType('paint').map(e=>e.toJSON())})};
}
