import {chromium} from 'playwright';import assert from 'node:assert/strict';import path from 'node:path';import fs from 'node:fs';import {serve} from './serve.mjs';import {observeBrowser} from './observe.mjs';import {inspectFrame,assertVisibleFrame} from './assertions.mjs';
const root=path.resolve(import.meta.dirname,'../..'),server=await serve(root),report={};
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':undefined),args:process.platform==='win32'?['--use-angle=d3d11']:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];page.setDefaultTimeout(45000);page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(observeBrowser);await page.addInitScript(()=>{localStorage.setItem('asfalto:nacional:v6:selected-vehicle','chevy_400_1957');});
const progress=setInterval(()=>page.evaluate(()=>({recovery:globalThis.__cockpit?.raceWorld?.getContextRecoveryState?.(),status:globalThis.__cockpit?.raceWorld?.getState().status,startup:globalThis.__asfaltoV7Startup?.diagnostics(),text:document.querySelector('.an-v7-load-state')?.textContent})).then(v=>console.log('FAULT FLOW',JSON.stringify(v))).catch(e=>console.log(e.message)),20000);
try{
 await page.goto(server.url+'?qa=1');await page.waitForFunction(()=>globalThis.__chevyV6Complete?.menuReady);await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelector('#an-intro')?.hidden!==false);await page.locator('[data-v6-panel=workshop]').click();await page.waitForFunction(()=>__chevyV6Complete.workshop.loaded,null,{timeout:180000});
 await page.locator('[data-v6-panel=drive]').click();await page.locator('[data-an-mode=drive]').click();await page.locator('#v6-drive-start').click();await page.locator('.an-v7-load-state [data-cancel]').click();await page.waitForFunction(()=>!document.body.classList.contains('an-loading-open')&&document.body.classList.contains('v6-menu-open'));report.cancel={passed:true,bootstrap:await page.evaluate(()=>__asfaltoV7Startup.diagnostics())};console.log('Cancellation passed');
 await page.locator('[data-v6-panel=drive]').click();if(await page.locator('[data-an-mode=drive]').isVisible())await page.locator('[data-an-mode=drive]').click();await page.locator('#v6-drive-start').click();await page.waitForFunction(()=>globalThis.__cockpit?.raceWorld?.getState().status==='RUNNING',null,{timeout:360000});console.log('Retry entered race');
 await page.evaluate(()=>{const gl=document.querySelector('#viewport canvas').getContext('webgl2');globalThis.__testContextExtension=gl.getExtension('WEBGL_lose_context');if(!__testContextExtension)throw Error('No WEBGL_lose_context');__testContextExtension.loseContext();});await page.waitForFunction(()=>__cockpit.raceWorld.getContextRecoveryState().state==='lost');assert.equal(await page.evaluate(()=>__cockpit.raceWorld.getState().status),'PAUSED');await page.evaluate(()=>__testContextExtension.restoreContext());await page.waitForFunction(()=>{const r=__cockpit.raceWorld.getContextRecoveryState();if(r.state==='failed')throw Error(r.error);return r.state==='ready';},null,{timeout:240000});await page.locator('[data-pause-action=resume]').click();await page.waitForFunction(()=>__cockpit.raceWorld.getState().status==='RUNNING');await page.waitForTimeout(1000);report.restored=await inspectFrame(page,await page.screenshot({path:'test-results/no-freeze/restored-context.png'}));assertVisibleFrame(report.restored);console.log('Context recovery passed');
 await page.evaluate(async()=>{__chevyV6Complete.workshop.releaseScene();await __asfaltoV6Modular.shutdown();});await page.waitForFunction(()=>__noFreezeAudit.snapshot().audio.every(a=>a.state==='closed'));report.frames=await page.evaluate(()=>__asfaltoFrames.diagnostics());report.retired=await page.evaluate(()=>__noFreezeAudit.snapshot());assert.equal(report.retired.pendingRaf,0,'Retired runtime still schedules frames');for(const gl of report.retired.gl)for(const [kind,count]of Object.entries(gl.resources))assert.equal(count.live,0,'GPU resources alive after shutdown: '+gl.id+' '+kind);for(const worker of report.retired.workerEvents.filter(e=>e.type==='create'))assert(report.retired.workerEvents.some(e=>e.type==='terminate'&&e.id===worker.id),'Worker outlived runtime');assert.deepEqual(errors,[]);assert.deepEqual(report.retired.errors,[]);report.passed=true;console.log('Full GPU/audio retirement passed');
}catch(error){report.failure=error.stack;report.state=await page.evaluate(()=>({recovery:globalThis.__cockpit?.raceWorld?.getContextRecoveryState?.(),invalidated:globalThis.__asfaltoInvalidatedPreparation,audit:__noFreezeAudit.snapshot()}));await page.screenshot({path:'test-results/no-freeze/runtime-fault-failure.png'});throw error;}finally{clearInterval(progress);report.errors=errors;fs.mkdirSync(path.join(root,'test-results/no-freeze'),{recursive:true});fs.writeFileSync(path.join(root,'test-results/no-freeze/runtime-faults.json'),JSON.stringify(report,null,2));await browser.close();await server.close();}
