import {engineGLTFLoaderClass} from './engine-gltf-loader-factory.mjs';
import {createEngineMechanism} from './engine-mechanism.mjs';
import {cycleState} from './engine-chevy-math.mjs';
import {resolveWorkshopEngineMount} from './vehicle-engine-mount.mjs';
const normalized=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
const textureKeys=['map','normalMap','roughnessMap','metalnessMap','emissiveMap','aoMap','bumpMap'];
export function createWorkshopEngine(T,workshop){
 const menu=document.getElementById('v6-main-menu'),page=menu.querySelector('[data-workshop-page="mechanics"]'),listeners=[],abort=new AbortController();let model=null,mechanism=null,pending=null,disposed=false,hood=0,selected=null,technical=false,cut=false,cutAxis='x',cutOffset=0,hidden=new Set(),env=null,partButtons=[],lastUi=0,loadFailed=false,autoRotate=false;const previousClipping=workshop.renderer.localClippingEnabled;
 const owned={geometries:new Set(),materials:new Set(),textures:new Set(),images:new Set()},baseEmissive=new Map(),meshOwners=new WeakMap(),mount=new T.Group(),plane=new T.Plane(),bounds=new T.Box3(),point=new T.Vector3(),q=new T.Quaternion();mount.name='Motor_Chevy_250_Interactive';mount.visible=false;workshop.car.add(mount);
 const vehicleId=workshop.vehicleId||workshop.vehiclePresentation.diagnostics().vehicle||'chevy';let mountFit=null;
 const carScale=workshop.car.scale.x||1;mount.scale.setScalar(1/carScale);mount.rotation.y=-Math.PI/2;
 const anchor=workshop.vehiclePresentation.root.getObjectByName('chevy_EngineBay_chevy_EngineBlock')||workshop.vehiclePresentation.root.getObjectByName('chevy_EngineBlock');
 if(anchor){bounds.setFromObject(anchor);bounds.getCenter(point);workshop.car.worldToLocal(point);mount.position.copy(point);}else mount.position.set(-.54,.006,0);
 const mountBasePosition=mount.position.clone();
 const hinge=workshop.vehiclePresentation.root.getObjectByName('chevy_HoodHinge'),hoodBox=hinge?new T.Box3().setFromObject(hinge):null;
 const modifications=document.createElement('details');modifications.className='an-engine-modifications';const summary=document.createElement('summary');summary.textContent='Modificaciones del auto';modifications.append(summary);for(const child of [...page.childNodes])if(!(child.nodeType===1&&child.classList.contains('an-hood-control')))modifications.append(child);page.append(modifications);
 const panel=document.createElement('section');panel.className='an-engine-panel';panel.setAttribute('aria-label','Motor Chevy 250 interactivo');panel.innerHTML=`<div class="an-engine-heading"><h3>Chevrolet 250</h3><span>Motor completo · 6 en línea</span></div><p class="an-engine-status" role="status">Abrí el capó para inspeccionar el motor.</p><button type="button" data-engine="load" class="v6-btn">Cargar motor</button><div class="an-engine-controls" hidden>
 <div class="an-engine-views" aria-label="Vistas del motor"><button data-view="three">3/4</button><button data-view="front">Frente</button><button data-view="side">Lateral</button><button data-view="top">Superior</button><button data-engine="fit">Encuadrar</button><button data-engine="rotate" aria-pressed="false">Giro automático</button><button data-engine="capture">Guardar foto</button></div>
 <div class="an-engine-tabs"><button data-engine="explore" aria-pressed="true">Explorar piezas</button><button data-engine="cycle" aria-pressed="false">Ciclo de trabajo</button></div>
 <div data-engine-page="explore"><label class="v6-field"><span>Buscar componente</span><input name="workshop-engine-part-search" type="search" aria-label="Buscar componente del motor" placeholder="Pistón, bujía, carburador…"></label><div class="an-engine-count"></div><div class="an-engine-parts" aria-label="Componentes del motor"></div><h4 class="an-engine-part-title">Conjunto mecánico</h4><p class="an-engine-part-description">Seleccioná una pieza en la lista o sobre el motor.</p><div class="an-engine-actions"><button data-engine="hide" disabled>Ocultar</button><button data-engine="isolate" disabled>Aislar</button><button data-engine="all">Ver todas</button></div></div>
 <div data-engine-page="cycle" hidden><p class="an-engine-cycle-label">Ciclo didáctico · distribución ilustrativa</p><div class="an-engine-cylinders"></div><div class="an-engine-actions"><button data-engine="play" aria-pressed="false">▶ Iniciar</button><button data-engine="internals">Ver mecanismo</button></div><label class="v6-field"><span>Velocidad <output data-output="speed">12 rpm</output></span><input name="workshop-engine-speed" aria-label="Velocidad didáctica del motor" data-slider="speed" type="range" min="2" max="30" value="12"></label><label class="v6-field"><span>Cigüeñal <output data-output="angle">0°</output></span><input name="workshop-engine-angle" aria-label="Ángulo del cigüeñal" data-slider="angle" type="range" min="0" max="720" value="0"></label></div>
 <label class="v6-field"><span>Despiece progresivo <output data-output="explode">0%</output></span><input name="workshop-engine-explode" aria-label="Despiece del motor" data-slider="explode" type="range" min="0" max="100" value="0"></label><div class="an-engine-actions"><button data-engine="cut" aria-pressed="false">Corte de inspección</button><button data-engine="reset">Restaurar motor</button></div><div class="an-engine-cut" hidden><select name="workshop-engine-cut-axis" aria-label="Eje de corte del motor"><option value="x">Transversal</option><option value="y">Horizontal</option><option value="z">Longitudinal</option></select><input name="workshop-engine-cut-offset" aria-label="Posición de corte del motor" type="range" min="-100" max="100" value="0"></div><details class="an-engine-facts"><summary>Ficha del modelo</summary><p>250 Plus · 6 cilindros en línea · 4,1 litros.<br>Distribución OHV · 12 válvulas.<br>Diámetro × carrera: 98,425 × 89,662 mm.<br>Orden de encendido: 1–5–3–6–2–4.</p></details><p class="an-engine-scope">Cinemática didáctica idealizada. El despiece y el corte ayudan a inspeccionar; las modificaciones se aplican abajo.</p></div>`;modifications.before(panel);
 const status=panel.querySelector('.an-engine-status'),controls=panel.querySelector('.an-engine-controls'),loadButton=panel.querySelector('[data-engine=load]'),parts=panel.querySelector('.an-engine-parts');
 const on=(o,event,fn)=>{o.addEventListener(event,fn);listeners.push(()=>o.removeEventListener(event,fn));};
 function collect(root){root.traverse(o=>{if(o.geometry)owned.geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])if(m){owned.materials.add(m);for(const key of textureKeys)if(m[key]){owned.textures.add(m[key]);if(m[key].source?.data?.close)owned.images.add(m[key].source.data);}}});}
 function release(){model?.removeFromParent();owned.geometries.forEach(g=>g.dispose());owned.materials.forEach(m=>m.dispose());owned.textures.forEach(t=>t.dispose());owned.images.forEach(i=>i.close());Object.values(owned).forEach(s=>s.clear());baseEmissive.clear();model=null;mechanism=null;selected=null;hidden.clear();partButtons=[];parts.replaceChildren();panel.querySelector('.an-engine-cylinders').replaceChildren();controls.hidden=true;mount.position.copy(mountBasePosition);}
 function active(){return !disposed&&hood>.05&&workshop.active;}
 function setRotate(value){autoRotate=!!value;panel.querySelector('[data-engine=rotate]').setAttribute('aria-pressed',String(autoRotate));}
 function suspend(){mechanism?.setPlaying(false);setRotate(false);syncCycle();}
 function setTechnical(value){technical=!!value;workshop.vehiclePresentation.root.visible=!technical;}
 function setEnvironment(texture){if(texture===env)return;env=texture;for(const material of owned.materials){material.envMap=texture;material.envMapIntensity=.7;material.needsUpdate=true;}}
 function setVisibility(){for(const g of mechanism.groups)g.visible=!hidden.has(g);filterParts();}
 function filterParts(){if(!mechanism)return;const search=normalized(panel.querySelector('input[type=search]').value);let count=0;for(const {group,button}of partButtons){button.hidden=!normalized([group.userData.label,group.userData.partId,group.userData.system].join(' ')).includes(search);if(!button.hidden)count++;button.classList.toggle('is-hidden',hidden.has(group));button.setAttribute('aria-pressed',String(group===selected));}panel.querySelector('.an-engine-count').textContent=`${count} / ${mechanism.groups.length} componentes · ${hidden.size} ocultos`;}
 function select(group){selected=group||null;for(const[material,base]of baseEmissive){material.emissive.copy(base.color);material.emissiveIntensity=base.intensity;}if(selected)selected.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material])if(m.emissive){m.emissive.set('#b75621');m.emissiveIntensity=.28;}});panel.querySelector('.an-engine-part-title').textContent=selected?.userData.label||'Conjunto mecánico';panel.querySelector('.an-engine-part-description').textContent=selected?.userData.description||'Seleccioná una pieza en la lista o sobre el motor.';for(const action of ['hide','isolate'])panel.querySelector(`[data-engine=${action}]`).disabled=!selected;panel.querySelector('[data-engine=hide]').textContent=hidden.has(selected)?'Mostrar':'Ocultar';filterParts();}
 function showAll(){hidden.clear();setVisibility();setTechnical(mechanism.diagnostics().explosion>0);}
 function setCut(value){cut=!!value;panel.querySelector('[data-engine=cut]').setAttribute('aria-pressed',String(cut));panel.querySelector('.an-engine-cut').hidden=!cut;for(const material of owned.materials){material.clippingPlanes=cut?[plane]:[];material.clipShadows=true;material.needsUpdate=true;}updatePlane();}
 function updatePlane(){if(!model||!cut)return;const center=assembled.getCenter(point),size=assembled.getSize(new T.Vector3());plane.normal.set(cutAxis==='x'?-1:0,cutAxis==='y'?-1:0,cutAxis==='z'?-1:0);plane.constant=center[cutAxis]+cutOffset*(size[cutAxis]/2+.04);model.updateWorldMatrix(true,false);plane.applyMatrix4(model.matrixWorld);}
 const assembled=new T.Box3();
 function fit(view='three',piece=null){if(!model)return;setRotate(false);const box=new T.Box3();if(piece)box.setFromObject(piece);else for(const mesh of mechanism.meshes){let visible=true;for(let p=mesh;p&&p!==model;p=p.parent)if(!p.visible)visible=false;if(visible)box.expandByObject(mesh);}if(box.isEmpty())return;const center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3()),direction=new T.Vector3(...(view==='front'?[0,.15,1]:view==='side'?[1,.2,0]:view==='top'?[.001,1,.001]:[1,.8,1.35])).normalize();mount.getWorldQuaternion(q);direction.applyQuaternion(q);const fov=workshop.camera.fov*Math.PI/180,distance=Math.max(.55,size.length()*.58/Math.sin(Math.min(fov/2,Math.atan(Math.tan(fov/2)*workshop.camera.aspect))));workshop.hotspots.engineDetail={target:center.toArray(),radius:distance,pitch:Math.asin(direction.y),yaw:Math.atan2(direction.x,direction.z)};workshop.focus('engineDetail');}
 function syncCycle(){if(!mechanism)return;const d=mechanism.diagnostics();panel.querySelector('[data-engine=play]').textContent=d.playing?'Ⅱ Pausar':'▶ Iniciar';panel.querySelector('[data-engine=play]').setAttribute('aria-pressed',String(d.playing));panel.querySelector('[data-output=angle]').textContent=Math.floor(d.angle)+'°';panel.querySelector('[data-slider=angle]').value=d.angle;panel.querySelector('[data-output=speed]').textContent=d.speedRpm+' rpm';panel.querySelector('[data-output=explode]').textContent=Math.round(d.explosion*100)+'%';for(let c=1;c<=6;c++){const state=cycleState(d.angle,c),el=panel.querySelector(`[data-cylinder="${c}"]`);el.textContent=`${c} · ${state.name}`;el.style.borderColor=state.color;}}
 function reset(){if(!mechanism)return;mechanism.reset();setRotate(false);hidden.clear();setVisibility();setTechnical(false);setCut(false);select(null);panel.querySelector('[data-slider=explode]').value=0;syncCycle();}
 async function ensureLoaded(){if(disposed)return null;if(mechanism)return mechanism;if(pending)return pending;loadFailed=false;panel.setAttribute('aria-busy','true');status.textContent='Cargando el motor completo…';loadButton.hidden=true;
 pending=(async()=>{const response=await fetch(new URL('../../assets/engine-chevy-250/Chevy_250_Serie_2.glb',import.meta.url),{signal:abort.signal});if(!response.ok)throw Error('No se pudo cargar el motor ('+response.status+').');const bytes=await response.arrayBuffer();const gltf=await new(engineGLTFLoaderClass(T))().parseAsync(bytes,'');model=gltf.scene;collect(model);if(disposed){release();return null;}mechanism=createEngineMechanism(T,model);
 for(const mesh of mechanism.meshes){let owner=mesh;while(owner&&!owner.userData.partId)owner=owner.parent;meshOwners.set(mesh,owner);mesh.castShadow=true;mesh.receiveShadow=true;const convert=material=>{const m=material.clone();owned.materials.add(m);m.side=T.DoubleSide;if(m.emissive)baseEmissive.set(m,{color:m.emissive.clone(),intensity:m.emissiveIntensity});if(owner?.userData.motion==='belt')for(const key of textureKeys)if(m[key]){m[key]=m[key].clone();m[key].wrapS=m[key].wrapT=T.RepeatWrapping;owned.textures.add(m[key]);}return m;};mesh.material=Array.isArray(mesh.material)?mesh.material.map(convert):convert(mesh.material);}
 assembled.setFromObject(model);const block=mechanism.groups.find(g=>g.userData.partId==='block'),blockCenter=new T.Box3().setFromObject(block||model).getCenter(new T.Vector3());
 const mounted=resolveWorkshopEngineMount(T,{vehicle:vehicleId,presentationRoot:workshop.vehiclePresentation.root,carRoot:workshop.car,engineBoundsM:{min:assembled.min.toArray(),max:assembled.max.toArray()},engineBlockCenterM:blockCenter.toArray()});
 if(mounted){if(!mounted.fit.contained)throw Error('El motor no cabe dentro del vano medido de este modelo.');mountFit=mounted.fit;mount.matrixAutoUpdate=!mounted.requiresMatrix;if(mounted.requiresMatrix)mount.matrix.copy(mounted.matrix);else{mount.position.copy(mounted.position);mount.quaternion.copy(mounted.quaternion);mount.scale.copy(mounted.scale);}}
 model.position.sub(blockCenter);mount.add(model);mount.updateWorldMatrix(true,true);if(!mounted&&hoodBox){const actual=new T.Box3().setFromObject(model),drop=actual.max.y-(hoodBox.max.y-.025);if(drop>0)mount.position.y-=drop/carScale;}workshop.renderer.localClippingEnabled=true;setEnvironment(workshop.presentation.getRoomEnvironment());workshop.vehiclePresentation.setEngineBayVisible?.(false);
 for(const group of [...mechanism.groups].sort((a,b)=>(a.userData.label||a.name).localeCompare(b.userData.label||b.name,'es',{numeric:true}))){const button=document.createElement('button');button.type='button';button.dataset.enginePart=group.userData.partId;button.textContent=group.userData.label||group.name;parts.append(button);partButtons.push({group,button});}
 for(let c=1;c<=6;c++){const el=document.createElement('span');el.dataset.cylinder=c;panel.querySelector('.an-engine-cylinders').append(el);}controls.hidden=false;status.textContent=`${mechanism.groups.length} componentes · selección sobre el modelo`;filterParts();syncCycle();mount.visible=active();if(hood>.5)fit();return mechanism;
 })().catch(error=>{release();if(!disposed){workshop.vehiclePresentation.setEngineBayVisible?.(true);setTechnical(false);loadFailed=true;status.textContent=error.message;loadButton.hidden=false;loadButton.textContent='Reintentar carga';}return null;}).finally(()=>{pending=null;panel.setAttribute('aria-busy','false');});return pending;}
 on(loadButton,'click',ensureLoaded);on(panel.querySelector('input[type=search]'),'input',filterParts);
 on(panel,'click',event=>{const part=event.target.closest('[data-engine-part]');if(part){select(mechanism?.groups.find(g=>g.userData.partId===part.dataset.enginePart));return;}const view=event.target.closest('[data-view]');if(view){fit(view.dataset.view);return;}const action=event.target.closest('[data-engine]')?.dataset.engine;if(!mechanism||!action)return;
 if(action==='explore'||action==='cycle'){for(const p of panel.querySelectorAll('[data-engine-page]'))p.hidden=p.dataset.enginePage!==action;for(const name of ['explore','cycle'])panel.querySelector(`[data-engine=${name}]`).setAttribute('aria-pressed',String(name===action));}
 if(action==='hide'&&selected){hidden.has(selected)?hidden.delete(selected):hidden.add(selected);setVisibility();select(selected);}
 if(action==='isolate'&&selected){hidden=new Set(mechanism.groups.filter(g=>g!==selected));setVisibility();setTechnical(true);fit('three',selected);}
 if(action==='rotate')setRotate(!autoRotate);if(action==='capture'){const url=workshop.capture();if(url){const link=document.createElement('a');link.href=url;link.download='Asfalto-Nacional-Chevrolet-250.png';link.click();}}if(action==='all')showAll();if(action==='fit')fit();if(action==='cut')setCut(!cut);if(action==='reset'){reset();fit();}if(action==='play'){mechanism.setPlaying(!mechanism.diagnostics().playing);syncCycle();}
 if(action==='internals'){hidden=new Set(mechanism.groups.filter(g=>!['rotativo','distribucion'].includes(g.userData.system)));setVisibility();setTechnical(true);fit();}
 });
 on(panel,'input',event=>{if(!mechanism)return;const kind=event.target.dataset.slider,value=Number(event.target.value);if(kind==='speed')mechanism.setSpeed(value);if(kind==='angle'){mechanism.setPlaying(false);mechanism.setAngle(value);}if(kind==='explode'){mechanism.setExplosion(value/100);if(value>0)setTechnical(true);else setTechnical(technical&&hidden.size>0);}syncCycle();});on(panel.querySelector('[data-slider=explode]'),'change',()=>fit());
 on(panel.querySelector('.an-engine-cut select'),'change',event=>{cutAxis=event.target.value;updatePlane();});on(panel.querySelector('.an-engine-cut input'),'input',event=>{cutOffset=Number(event.target.value)/100;updatePlane();});
 const ray=new T.Raycaster();let pointer=null;on(workshop.canvas,'pointerdown',e=>{setRotate(false);pointer={x:e.clientX,y:e.clientY,button:e.button};});on(workshop.canvas,'pointerup',e=>{if(!active()||!mechanism||!pointer||pointer.button!==0||Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>5)return;const rect=workshop.canvas.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2),workshop.camera);const hit=ray.intersectObjects([mount,workshop.vehiclePresentation.root],true).find(h=>{for(let p=h.object;p;p=p.parent)if(!p.visible)return false;return !meshOwners.has(h.object)||!cut||plane.distanceToPoint(h.point)>=0;});if(hit&&meshOwners.has(hit.object))select(meshOwners.get(hit.object));pointer=null;});
 on(workshop.canvas,'pointercancel',()=>{pointer=null;});on(workshop.canvas,'wheel',()=>setRotate(false));on(document,'visibilitychange',()=>{if(document.hidden)suspend();});
 const api={ensureLoaded,fit,reset,suspend,setHood(value){const was=hood;hood=clamp(value,0,1);if(hood>.01&&!mechanism&&!loadFailed)void ensureLoaded();if(was>.01&&hood<=.01){reset();}mount.visible=!!mechanism&&active();},update(dt){if(disposed)return;const visible=!!mechanism&&active();mount.visible=visible;if(!visible){if(mechanism?.diagnostics().playing){mechanism.setPlaying(false);syncCycle();}return;}setEnvironment(workshop.presentation.getRoomEnvironment());if(autoRotate&&!workshop.drag&&!workshop.targetPose&&!document.body.classList.contains('v6-reduce-motion')&&!matchMedia('(prefers-reduced-motion: reduce)').matches)workshop.yaw+=dt*.16;mechanism.update(dt);updatePlane();lastUi+=dt;if(lastUi>.08){syncCycle();lastUi=0;}},get root(){return mount;},get mechanism(){return mechanism;},diagnostics:()=>({vehicle:vehicleId,mountFit,loaded:!!mechanism,loading:!!pending,hood,active:active(),technical,autoRotate,cut,cutAxis,cutOffset,hidden:[...hidden].map(g=>g.userData.partId),selected:selected?.userData.partId||null,mechanism:mechanism?.diagnostics(),source:'Motor_Chevy_250/Chevy_250_Serie_2.glb'}),dispose(){if(disposed)return;disposed=true;abort.abort();if(workshop.renderer)workshop.renderer.localClippingEnabled=previousClipping;listeners.forEach(f=>f());workshop.vehiclePresentation.root.visible=true;workshop.vehiclePresentation.setEngineBayVisible?.(true);release();mount.removeFromParent();panel.remove();for(const child of [...modifications.childNodes])if(child!==summary)page.insertBefore(child,modifications);modifications.remove();}};return api;
}
