import { wrapRouteDistance, signedRouteDistance } from './route-distances.mjs?v=66a33fddb083fb2b';
const DYNAMICS = /(?:vehicle|tyre|tire|suspension|engine|brake|mass|aero|assist)/i;
const freeze = value => { if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value; Object.values(value).forEach(freeze); return Object.freeze(value); };
const finite = (value, name) => { if (!Number.isFinite(value)) throw new TypeError(name + ' must be finite'); return value; };
const lerp = (a,b,t) => a + (b-a)*t;
function sourceAt(route, distance) { const samples=route.samples; const s=route.closed?wrapRouteDistance(distance,route.lengthM):Math.max(0,Math.min(route.lengthM,distance)); let lo=0, hi=samples.length-1; while(lo+1<hi){const mid=(lo+hi)>>1;if(samples[mid].sM<=s)lo=mid;else hi=mid;} const a=samples[lo],b=samples[Math.min(lo+1,samples.length-1)]; const t=b===a?0:(s-a.sM)/(b.sM-a.sM); return {s,a,b,t}; }
export function createGameplayBridge(routeQuery, route, profile = {}) {
  if (!routeQuery || typeof routeQuery.sample !== 'function') throw new TypeError('routeQuery must be a route query');
  if (!route || !Array.isArray(route.samples) || !Number.isFinite(route.lengthM)) throw new TypeError('route must be canonical');
  const seenProfile = new Set(); const inspectProfile = value => { if (!value || typeof value !== 'object' || seenProfile.has(value)) return; seenProfile.add(value); for (const [key, child] of Object.entries(value)) { if (DYNAMICS.test(key)) throw new TypeError('profile must not contain vehicle dynamics: ' + key); inspectProfile(child); } }; inspectProfile(profile);
  const length=route.lengthM, shoulder=Number.isFinite(profile.shoulder)?profile.shoulder:.9, barrier=Number.isFinite(profile.barrier)?profile.barrier:2.8;
  if (shoulder < 0 || barrier < shoulder) throw new TypeError('profile shoulder/barrier are invalid');
  function sample(distance) { finite(distance,'distance'); const {s,a,b,t}=sourceAt(route,distance); const tx=lerp(a.tangent[0],b.tangent[0],t),ty=lerp(a.tangent[1],b.tangent[1],t),tz=lerp(a.tangent[2],b.tangent[2],t), n=Math.hypot(tx,ty,tz)||1, heading=Math.atan2(tx/n,-tz/n); return Object.freeze({s,u:s/length,sectorId:t<.5?a.sectorId:b.sectorId,x:lerp(a.position[0],b.position[0],t),y:lerp(a.position[1],b.position[1],t),z:lerp(a.position[2],b.position[2],t),tx:tx/n,ty:ty/n,tz:tz/n,rx:Math.cos(heading),rz:Math.sin(heading),heading,curvature:lerp(Number(a.curvaturePerM)||0,Number(b.curvaturePerM)||0,t),width:lerp(a.widthM,b.widthM,t),bank:lerp(Number(a.bank)||0,Number(b.bank)||0,t),targetSpeedKph:lerp(Number(a.targetSpeedKmh)||0,Number(b.targetSpeedKmh)||0,t)}); }
  const widthAt = d => {finite(d,'distance');const {a,b,t}=sourceAt(route,d);return lerp(a.widthM,b.widthM,t);}, bankAt=d=>{finite(d,'distance');const {a,b,t}=sourceAt(route,d);return lerp(Number(a.bank)||0,Number(b.bank)||0,t);};
  function idealLineOffset(d){finite(d,'distance');const now=sample(d),next=sample(d+35),turn=Math.max(-1,Math.min(1,now.curvature*130+next.curvature*75));return -turn*now.width*.16;}
  function surfaceAt(d,lateral,half=0){finite(d,'distance');finite(lateral,'lateral');finite(half,'vehicleHalfWidth');if(half<0)throw new TypeError('vehicleHalfWidth must be nonnegative');const edge=widthAt(d)/2-Math.max(0,half),abs=Math.abs(lateral),side=lateral<0?-1:1;if(abs<=edge)return freeze({kind:'asphalt',grip:1,drag:.006,roughness:.02,side});if(abs<=edge+.36)return freeze({kind:'curb',grip:.86,drag:.04,roughness:.62,side});if(abs<=edge+shoulder)return freeze({kind:'shoulder',grip:.72,drag:.15,roughness:.35,side});if(abs>=edge+barrier)return freeze({kind:'barrier',grip:.25,drag:1.8,roughness:1,side});return freeze({kind:'grass',grip:.48,drag:.58,roughness:.72,side});}
  function resolveBarrierCollision(d,lateral,speed=0,half=.91){finite(d,'distance');finite(lateral,'lateral');finite(speed,'lateralSpeedMps');finite(half,'vehicleHalfWidth');if(half<0)throw new TypeError('vehicleHalfWidth must be nonnegative');const allowed=widthAt(d)/2+barrier-Math.max(0,half);if(Math.abs(lateral)<=allowed)return freeze({collided:false,lateral,lateralSpeedMps:speed});const side=lateral<0?-1:1;return freeze({collided:true,lateral:side*allowed,lateralSpeedMps:speed*side>0?-speed*.08:speed});}
  const checkpoints=freeze((route.sectors || []).map(x => x.endM)); let maxCurvature=0; route.samples.forEach(x=>maxCurvature=Math.max(maxCurvature,Math.abs(Number(x.curvaturePerM)||0)));
  return freeze({id:profile.id||'point_to_point',name:profile.name||profile.id||'Point to point',description:profile.description||'',biome:profile.biome||'mountain',environment:profile.environment||'clear',seed:Number.isFinite(profile.seed)?profile.seed:501,palette:freeze(profile.palette||{}),shoulder,barrier,closed:route.closed===true,length,maxCurvature,checkpoints,speedTrap:freeze(profile.speedTrap||{}),brakingMarkers:freeze(profile.brakingMarkers||[]),sample,widthAt,bankAt,idealLineOffset,surfaceAt,resolveBarrierCollision,forwardDistance(from,to){finite(from,'from');finite(to,'to');return route.closed?wrapRouteDistance(to-from,length):Math.max(0,Math.min(length,to))-Math.max(0,Math.min(length,from));},shortestDistance(from,to){finite(from,'from');finite(to,'to');return route.closed?signedRouteDistance(from,to,length):Math.max(0,Math.min(length,to))-Math.max(0,Math.min(length,from));},routeQuery});
}