import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createStartupDemand} from '../src/runtime/startup-demand.mjs?v=d7f04a8f3c4b6613';
import {createSessionTransactionRunner} from '../src/menu/v7-session-runtime.mjs?v=4964050ed6c0f11e';
import {createTrackManager} from '../src/tracks/track-manager.mjs?v=02570a5c5fd67f0a';
const tick=()=>new Promise(r=>setImmediate(r));
const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
async function bounded(promise,ms=150){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>timer=setTimeout(()=>reject(Error('operation did not settle within bound')),ms))]);}finally{clearTimeout(timer);}}
function fixture(loader){const adapters=[];const registry={schema:'asfalto-track-registry/v1',tracks:['one','two'].map(id=>({id,status:'ready',manifest:`./tracks/${id}/manifest.json`}))};const manager=createTrackManager({registry,createAdapter:id=>{const a={id,ready:false,unloads:0};for(const k of ['validate','sampleRoute','projectToRoute','surfaceAt','resolveRespawn','getSpawn','getCheckpoints','updateStreaming','applyEnvironment','getDiagnostics'])a[k]=()=>{};a.load=async opts=>{await loader(id,opts);a.ready=true;};a.unload=async()=>{a.ready=false;a.unloads++;};adapters.push(a);return a;}});return{manager,adapters};}
test('A1 session cancellation closes UI without awaiting a non-cooperative load',async()=>{const blocked=defer();let ends=0,cancels=0;const runner=createSessionTransactionRunner({begin:()=>({end(){ends++;}}),onCancel(){cancels++;}});const result=runner.run(async()=>{await blocked.promise;return true;});await tick();runner.cancel();try{assert.equal(await bounded(result),false);assert.equal(ends,1);assert.equal(cancels,1);assert.equal(runner.diagnostics().active,false);}finally{blocked.resolve();await result;}});
test('A1 timeout rejects startup even if loader ignores abort, retry owns final result',async()=>{const blocked=defer();let count=0;const gate=createStartupDemand({prepareTimeoutMs:15});const runtime=gate.run(()=>++count===1?blocked.promise:'new');try{await assert.rejects(bounded(gate.request()),{name:'TimeoutError'});assert.equal(gate.diagnostics().phase,'failed');await bounded(gate.request());assert.equal(await bounded(runtime),'new');blocked.resolve('stale');await tick();assert.equal(gate.diagnostics().phase,'prepared');}finally{blocked.resolve('stale');}});
test('A1 immediate request after last cancel is not rejected by the old attempt',async()=>{const blocked=defer(),abort=new AbortController();let count=0;const gate=createStartupDemand({prepareTimeoutMs:80});const runtime=gate.run(()=>++count===1?blocked.promise:'fresh');const first=gate.request({signal:abort.signal});first.catch(()=>{});await tick();abort.abort();const next=gate.request();try{await assert.rejects(first,{name:'AbortError'});await bounded(next);assert.equal(await bounded(runtime),'fresh');}finally{blocked.resolve('old');}});
test('A1 manager forwards abort and never commits a late loaded adapter',async()=>{const blocked=defer(),abort=new AbortController();let loadSignal;const {manager,adapters}=fixture(async(id,{signal})=>{if(id==='two'){loadSignal=signal;await blocked.promise;}});await manager.select('one');const second=manager.select('two',{signal:abort.signal});second.catch(()=>{});await tick();abort.abort();try{await assert.rejects(bounded(second),{name:'AbortError'});assert.equal(loadSignal.aborted,true);assert.equal(manager.active.id,'one');blocked.resolve();await tick();await tick();assert.equal(manager.active.id,'one');assert.equal(adapters[1].unloads,1);}finally{blocked.resolve();await second.catch(()=>{});await manager.unload();}});
test('A1 unload does not wait forever for an aborted pending adapter',async()=>{const blocked=defer();const {manager,adapters}=fixture(()=>blocked.promise);const selected=manager.select('one');selected.catch(()=>{});await tick();try{await bounded(manager.unload());assert.equal(manager.active,null);await assert.rejects(bounded(selected),{name:'AbortError'});blocked.resolve();await tick();await tick();assert.equal(adapters[0].unloads,1);}finally{blocked.resolve();await selected.catch(()=>{});}});
test('A1 manager selection has a finite timeout and preserves active track',async()=>{const blocked=defer();const {manager}=fixture(id=>id==='two'?blocked.promise:undefined);await manager.select('one');const attempt=manager.select('two',{timeoutMs:15});try{await assert.rejects(bounded(attempt),{name:'TimeoutError'});assert.equal(manager.active.id,'one');}finally{blocked.resolve();await attempt.catch(()=>{});await manager.unload();}});
test('A1 active host and bootstrap forward the caller signal to track selection',()=>{const host=fs.readFileSync(new URL('../src/legacy/module-02.mjs?v=137fa1d93f159138',import.meta.url),'utf8');const bootstrap=fs.readFileSync(new URL('../src/app/modular-bootstrap.mjs?v=d42221a6484c9e05',import.meta.url),'utf8');assert.match(host,/facade\.selectTrack\(id,\s*\{signal\}\)/);assert.match(bootstrap,/manager\.select\(id,\s*\{signal/);});
test('A1 presentation exceptions cannot retain the active transaction',async()=>{const runner=createSessionTransactionRunner({begin:()=>{throw Error('surface-create');}});await assert.rejects(runner.run(async()=>true),/surface-create/);assert.equal(runner.diagnostics().active,false);const runner2=createSessionTransactionRunner({begin:()=>({end(){throw Error('surface-end');}})});await assert.rejects(runner2.run(async()=>true),/surface-end/);assert.equal(runner2.diagnostics().active,false);});
test('A1 readiness polling stops on abort and presentation-frame errors reject',async()=>{const helpers=await import('../src/runtime/abortable.mjs?v=c91114c944607feb');assert.equal(typeof helpers.waitForCondition,'function');assert.equal(typeof helpers.waitForAnimationFrame,'function');let calls=0;const c=new AbortController();const p=helpers.waitForCondition(()=>{calls++;return false;},{signal:c.signal,intervalMs:2,timeoutMs:50});await tick();c.abort();await assert.rejects(p,{name:'AbortError'});const n=calls;await new Promise(r=>setTimeout(r,6));assert.equal(calls,n);await assert.rejects(helpers.waitForCondition(()=>false,{intervalMs:2,timeoutMs:5}),{name:'TimeoutError'});await assert.rejects(helpers.waitForAnimationFrame(undefined,()=>{throw Error('frame failure');},{requestFrame:fn=>setImmediate(fn),cancelFrame:clearImmediate}),/frame failure/);});
