import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {THREE as T}from'./cinematic-three.mjs';
const url=new URL('../src/render/render-budget.mjs',import.meta.url);
async function budgetModule(){assert.ok(fs.existsSync(url),'explicit render budget must exist');return import(url);}
test('A7 combined HDR budget bounds physical pixels and nominal bytes for all profiles and DPR',async()=>{const {resolveRenderBudget}=await budgetModule();for(const phone of [false,true])for(const quality of ['cinematic','high','balanced','low','off'])for(const pixelRatio of [1,1.9,3]){const b=resolveRenderBudget({width:3840,height:2160,pixelRatio,quality,phone});assert.ok(b.width*b.height<=b.maxPixels);assert.ok(b.nominalPostBytes<=b.maxPostBytes);assert.ok(b.pixelRatio<=pixelRatio);assert.ok(b.width>=2&&b.height>=2);assert.ok(Math.abs(b.width/b.height-3840/2160)<.01);}});
test('A7 ordinary 640x360 rendering is not enlarged or unnecessarily reduced',async()=>{const {resolveRenderBudget}=await budgetModule();const b=resolveRenderBudget({width:640,height:360,pixelRatio:1,quality:'cinematic'});assert.deepEqual([b.width,b.height,b.pixelRatio],[640,360,1]);});
test('A4 workshop renderer actually applies governed scale and shadow policy, restores on dispose',async()=>{const {createWorkshopRenderBudget}=await budgetModule();let ratio=1,size=new T.Vector2(640,360),sets=0;const renderer={domElement:{getBoundingClientRect:()=>({width:640,height:360}),addEventListener(){},removeEventListener(){}},shadowMap:{enabled:true},getPixelRatio:()=>ratio,setPixelRatio(v){ratio=v;sets++;},getSize:v=>v.copy(size),setSize(w,h){size.set(w,h);sets++;}};const b=createWorkshopRenderBudget(T,{renderer});b.apply('high');b.apply('low');assert.equal(ratio,.7);assert.equal(renderer.shadowMap.enabled,false);assert.equal(b.diagnostics().width,448);const before=sets;b.apply('low');assert.equal(sets,before,'stable dimensions do not resize every frame');b.apply('high');assert.equal(ratio,1);assert.equal(renderer.shadowMap.enabled,true);b.dispose();assert.equal(ratio,1);});
test('A4 advanced graphics owns a real applied workshop renderer policy, not just labels',async()=>{const {createAdvancedGraphics}=await import('../src/render/advanced-graphics.mjs');const old=globalThis.__asfaltoV7Storage;globalThis.__asfaltoV7Storage={getItem:()=>JSON.stringify({quality:'cinematic',gtao:false,ssgi:false,dfao:false,volumetrics:false,materials:false,sky:false,pdo:false,pivotPainter:false})};let ratio=1;const renderer={info:{memory:{textures:0,geometries:0}},capabilities:{maxSamples:0},getContext:()=>({isContextLost:()=>false}),render(){},shadowMap:{enabled:true},domElement:{getBoundingClientRect:()=>({width:640,height:360}),addEventListener(){},removeEventListener(){}},getSize:v=>v.set(640,360),setSize(){},getPixelRatio:()=>ratio,setPixelRatio:v=>ratio=v};const api=createAdvancedGraphics(T,{renderer,scene:new T.Scene(),camera:new T.PerspectiveCamera(),scope:'workshop',getMaximumQuality:()=> 'high'});try{for(let i=0;i<50;i++){api.update({time:i*.1});api.render(()=>{});}assert.equal(api.getEffectiveQuality(),'low');assert.equal(ratio,.7);assert.equal(renderer.shadowMap.enabled,false);assert.equal(api.diagnostics().rendererBudget.quality,'low');}finally{api.dispose();globalThis.__asfaltoV7Storage=old;}});

test('A7 actual postprocess targets change MSAA on downgrade, obey allocation bounds, and reuse support queries',async()=>{
 const {allocationRenderer}=await import('./helpers-renderer.mjs');const {createScreenSpaceLighting}=await import('../src/render/screen-space-lighting.mjs');const {createRaceColorGrade}=await import('../src/render/race-color-grade.mjs');
 const r=allocationRenderer(3648,2052);let quality='cinematic';const p=createScreenSpaceLighting(T,{renderer:r,scene:new T.Scene(),camera:new T.PerspectiveCamera(),quality,samples:4});const c=createRaceColorGrade({THREE:T,renderer:r,getQuality:()=>quality,samples:4});await c.setSettings({contrast:1.02});
 try{c.render(()=>p.render(()=>{}));for(const tier of ['cinematic','high','low','balanced','cinematic']){quality=tier;p.setQuality(tier);c.render(()=>p.render(()=>{}));const pd=p.diagnostics(),cd=c.diagnostics();assert.ok(pd.size[0]*pd.size[1]<=pd.allocationBudget.maxPixels);assert.ok(cd.allocation.width*cd.allocation.height<=cd.allocationBudget.maxPixels);if(tier==='low'){assert.equal(pd.samples,0,'Low really releases MSAA');assert.equal(cd.samples,0,'LUT cannot retain high MSAA after a downgrade');}assert.ok(pd.allocations.reduce((n,x)=>n+x.nominalBytes,0)+cd.allocation.nominalBytes<=cd.allocationBudget.maxPostBytes);const queries=r.queries;c.render(()=>p.render(()=>{}));assert.equal(r.queries,queries,'format support is not queried every frame');}}
 finally{p.dispose();c.dispose();}assert.equal(p.diagnostics().targets,0);assert.equal(c.diagnostics().renderTargetAllocated,false);
});
