import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {computeWaterField,computeRoadField} from '../src/render/hydrology-compute.mjs?v=d280021eea2b85af';
const fixtures=JSON.parse(fs.readFileSync(new URL('./fixtures/hydrology-reference.json?v=afef1f37a0cdeada',import.meta.url)));
for(const [i,f]of fixtures.entries())test('hydrology typed CPU output matches pre-worker reference '+i,()=>{const input={...f.input};for(const key of ['segments','depthSamples','positions'])if(input[key])input[key]=new Float64Array(input[key]);const values=f.kind==='water'?computeWaterField(input):computeRoadField(input);assert.equal(createHash('sha256').update(new Uint8Array(values.buffer)).digest('hex'),f.sha256);});

import {createHydrologyJobs} from '../src/render/hydrology-jobs.mjs?v=3415d1d281b4f2e9';
import {createWaterHydrology,installRoadHydrology} from '../src/render/weather-hydrology.mjs?v=02f1a8ed11382fce';
import {THREE as T} from './cinematic-three.mjs?v=1538801f0545ceb6';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function fakeWorkers(){const all=[];return {all,workerFactory(){const worker={messages:[],terminated:false,postMessage(message,transfers){this.messages.push(structuredClone(message,{transfer:transfers}));},terminate(){this.terminated=true;}};all.push(worker);return worker;}};}
test('worker transfers its copy and cancel cannot disturb a later job',async()=>{const fake=fakeWorkers(),jobs=createHydrologyJobs(fake),signal=new AbortController(),input={positions:new Float64Array([0,0,0])};const first=jobs.run('road',input,{signal:signal.signal}),reject=assert.rejects(first,{name:'AbortError'});assert.equal(input.positions.byteLength,24);const old=fake.all[0];signal.abort();await reject;assert.equal(old.terminated,true);const next=jobs.run('road',input),current=fake.all[1];old.onerror({message:'late error'});assert.equal(current.terminated,false);current.onmessage({data:{id:current.messages[0].id,values:new Float32Array([0,0]),computeMs:1}});assert.deepEqual(await next,new Float32Array([0,0]));assert.equal(jobs.diagnostics().pending,0);jobs.dispose();});
test('worker error rejects pending jobs and a new worker may recover',async()=>{const fake=fakeWorkers(),jobs=createHydrologyJobs(fake),a=jobs.run('road',{positions:new Float64Array([0,0,0])}),b=jobs.run('road',{positions:new Float64Array([1,0,0])});const failures=[assert.rejects(a,/failed/),assert.rejects(b,/failed/)];fake.all[0].onerror({message:'failed'});await Promise.all(failures);assert.equal(jobs.diagnostics().pending,0);jobs.dispose();});
test('worker timeout is bounded and releases all jobs',async()=>{const fake=fakeWorkers(),jobs=createHydrologyJobs({...fake,timeoutMs:10});await assert.rejects(jobs.run('road',{positions:new Float64Array([0,0,0])}),/timed out/);assert.equal(fake.all[0].terminated,true);assert.equal(jobs.diagnostics().pending,0);jobs.dispose();});
test('late hydrology results cannot resurrect a disposed water texture or road attribute',async()=>{const waterJob=deferred(),roadJob=deferred(),mesh=new T.Mesh(new T.PlaneGeometry(12,12).rotateX(-Math.PI/2),new T.MeshStandardMaterial()),field=createWaterHydrology(T,mesh,{jobs:{run:()=>waterJob.promise}}),initial=field.texture.image.data,restore=installRoadHydrology(T,mesh,{jobs:{run:()=>roadJob.promise}});field.dispose();restore();waterJob.resolve(new Float32Array(96*96*4));roadJob.resolve(new Float32Array(mesh.geometry.attributes.position.count*2));assert.equal(await field.ready,false);assert.equal(await restore.ready,false);assert.equal(field.texture.image.data,initial);assert.equal(mesh.geometry.getAttribute('anFxHydrology'),undefined);});
test('worker failure uses the exact synchronous water and road fallback',async()=>{const jobs={run:()=>Promise.reject(Error('Unavailable'))},mesh=new T.Mesh(new T.PlaneGeometry(24,24,8,8).rotateX(-Math.PI/2),new T.MeshStandardMaterial());const expected=createWaterHydrology(T,mesh),actual=createWaterHydrology(T,mesh,{jobs});await actual.ready;assert.deepEqual(actual.texture.image.data,expected.texture.image.data);assert.equal(actual.diagnostics.worker,false);const original=installRoadHydrology(T,mesh),road=mesh.geometry.attributes.anFxHydrology.array.slice();original();const restore=installRoadHydrology(T,mesh,{jobs});await restore.ready;assert.deepEqual(mesh.geometry.attributes.anFxHydrology.array,road);restore();actual.dispose();expected.dispose();});
