import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {waitForSignal} from '../src/runtime/abortable.mjs?v=c91114c944607feb';import {createSessionTransactionRunner} from '../src/menu/v7-session-runtime.mjs?v=4964050ed6c0f11e';
const moduleSource=readFileSync(new URL('../src/legacy/module-02.mjs?v=137fa1d93f159138',import.meta.url),'utf8'),menuSource=readFileSync(new URL('../src/legacy/v6-complete-runtime.js?v=ab035c041897b730',import.meta.url),'utf8');
const extract=(s,start,end)=>s.slice(s.indexOf(start),s.indexOf(end,s.indexOf(start))).trim();
const bind=(source,scope)=>new Function('scope',`with(scope){return (${source});}`)(scope);
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};const tick=()=>new Promise(r=>setImmediate(r));
const prepareSource=extract(moduleSource,'  let renderingPreparation=','  gpuFrameTimer=createGpuFrameTimer');
const bindPrepare=scope=>new Function('scope',`with(scope){${prepareSource};return prepareRendering;}`)(scope);
for(const hidden of ['v6-menu-open','an-intro-open'])test('no world work behind '+hidden,()=>{const render=bind(extract(moduleSource,'  function renderFrame() {','  function qualityPixelRatioLimit('),{bootRenderGate:{allowed:()=>true},document:{body:{classList:{contains:s=>s===hidden}}},markFirstFrame(){throw Error('unseen frame prepared');}});render();});
function configuration(){const calls=[],selected=deferred(),compiled=deferred(),controller=new AbortController();let current=true;const cockpit={raceGetState:()=>({track:{id:'old'}}),raceSelectCircuit:async()=>calls.push('track'),prepareRendering:()=>{calls.push('compile');return compiled.promise;}};const scope={profile:{lastSky:'clear'},workshop:{raceVehicleSelection:{ensureApplied:()=>{calls.push('selection');return selected.promise;}}},waitForExistingGameReady:async()=>cockpit,persistedTrack:x=>x,normalizeTrack:x=>x,reflectValue(){},setValue(){},clamp:x=>x,toast(){}};const fn=bind(extract(menuSource,'async function configureExistingGameReady(','function persistPlayableRoute('),scope),tx={signal:controller.signal,isCurrent:()=>current&&!controller.signal.aborted,wait:p=>waitForSignal(p,controller.signal),stage(){}};return{calls,selected,compiled,cancel(){current=false;controller.abort();},run:()=>fn({track:'dos_lagos',weather:'clear',mode:'practice',laps:1,difficulty:'normal'},tx)};}
test('selection and shaders must settle before race configuration can succeed',async()=>{const f=configuration();let done=false;const p=f.run().then(x=>{done=true;return x});await tick();assert.deepEqual(f.calls,['selection']);f.selected.resolve();await tick();assert.deepEqual(f.calls,['selection','track','compile']);assert.equal(done,false);f.compiled.resolve();assert.equal(await p,true);});
test('failed selected car cannot configure route or compile',async()=>{const f=configuration(),p=f.run();const rejected=assert.rejects(p,/vehicle failed/);f.selected.reject(Error('vehicle failed'));await rejected;assert.deepEqual(f.calls,['selection']);});
test('shader failure never reports ready',async()=>{const f=configuration(),p=f.run();f.selected.resolve();await tick();const rejected=assert.rejects(p,/compile failed/);f.compiled.reject(Error('compile failed'));await rejected;});
test('cancel during compile aborts immediately and never reports ready after late completion',async()=>{const f=configuration(),p=f.run();f.selected.resolve();await tick();const rejected=assert.rejects(p,{name:'AbortError'});f.cancel();await rejected;f.compiled.resolve();await tick();});
test('shader preparation serializes and checks shutdown after compile',async()=>{const gates=[],calls=[];let shutdown=false;const fn=bindPrepare({bootRenderGate:{release(){throw Error('Failed preparation cannot release render gate');}},modularHostInitialization:{assertActive(){if(shutdown)throw Error('shutdown');},waitFor:p=>p},applyMechanicalVisuals(){calls.push('mechanical');},updateRaceCamera(dt){assert.equal(dt,0);},advancedGraphics:{update(){}},performance:{now:()=>0},cockpitRenderPass:{prepare(){const g=deferred();gates.push(g);return g.promise;}}});const a=fn(),b=fn();await tick();assert.equal(gates.length,1);const rejected=assert.rejects(a,/compile failed/);gates[0].reject(Error('compile failed'));await rejected;await tick();assert.equal(gates.length,2);shutdown=true;const stopped=assert.rejects(b,/shutdown/);gates[1].resolve();await stopped;assert.equal(calls.length,2);});
test('actual drive flow waits for configuration and race start before exposing the scene',async()=>{const configuration=deferred(),started=deferred(),events=[];const runner=createSessionTransactionRunner();const scope={canLeaveWorkshop:()=>true,leaveChampionship:async()=>{},cancelRoadTest(){},profile:{},saveProfile:async()=>{},q:()=>({value:'dos_lagos'}),getSessionRequestRunner:async()=>runner,workshop:{},configureExistingGameReady:()=>configuration.promise,persistPlayableRoute:x=>x,applyVehicleConfig(){},resetSession(){},activeSession:{},performance:{now:()=>1},window:{__cockpit:{raceStart:()=>{events.push('race-start');return started.promise;}}},openPreparedRace:()=>{events.push('open');return true;},toast(){},sessionLoop:{start(){}}};const fn=bind(extract(menuSource,'async function startDrive(mode){','async function startRoadTest('),scope),p=fn('free');await tick();assert.deepEqual(events,[]);configuration.resolve(true);await tick();assert.deepEqual(events,['race-start']);started.resolve();assert.equal(await p,true);assert.deepEqual(events,['race-start','open']);});
test('launch guard rejects overlapping preparations and releases on failure',async()=>{const gates=[],body=extract(menuSource,'let gameLaunchPreparing=false;','async function prepareExistingGame('),fn=new Function('prepareExistingGame',body+';return configureExistingGame;')(()=>{const g=deferred();gates.push(g);return g.promise;});const p=fn({});assert.equal(await fn({}),false);gates[0].resolve(true);assert.equal(await p,true);const q=fn({}),rejected=assert.rejects(q,/failure/);gates[1].reject(Error('failure'));await rejected;const z=fn({});gates[2].resolve(true);assert.equal(await z,true);});

test('phone render gate opens only after selected shaders complete successfully',async()=>{const compiled=deferred();let released=false;const prepare=bindPrepare({bootRenderGate:{release(){released=true;}},modularHostInitialization:{assertActive(){},waitFor:p=>p},applyMechanicalVisuals(){},updateRaceCamera(){},advancedGraphics:{update(){}},performance:{now:()=>0},cockpitRenderPass:{prepare:()=>compiled.promise}});const p=prepare();await tick();assert.equal(released,false);compiled.resolve();await p;assert.equal(released,true);});
