import test from 'node:test';import assert from 'node:assert/strict';import {snapshotSceneResources} from '../src/runtime/scene-resources.mjs?v=df7fa85b2177e284';
test('scene cleanup releases instance buffers, shadows and owned images, preserving borrowed assets',()=>{const calls=[];const resource=name=>({dispose:()=>calls.push(name)});const bitmap={close:()=>calls.push('bitmap')},shared={...resource('shared'),isTexture:true,image:{close:()=>calls.push('shared-image')}};const material={...resource('material'),map:{...resource('texture'),isTexture:true,image:bitmap},envMap:shared};const node={...resource('instance'),isInstancedMesh:true,geometry:resource('geometry'),material,shadow:resource('shadow')};const root={traverse:fn=>fn(node)},borrowed={traverse:fn=>fn({material:{map:shared}})};const owned=snapshotSceneResources(root,{borrowedRoots:[borrowed]});assert(owned.dispose());assert.equal(owned.dispose(),false);assert.deepEqual(calls.sort(),['bitmap','geometry','instance','material','shadow','texture']);});

import {THREE} from './cinematic-three.mjs?v=1538801f0545ceb6';import {installRoadHydrology} from '../src/render/weather-hydrology.mjs?v=dba2951eead82e3a';
test('road attribute cleanup releases GPU attributes before detaching them',()=>{const mesh=new THREE.Mesh(new THREE.PlaneGeometry(10,10,3,3));let freed=0;mesh.geometry.addEventListener('dispose',()=>{assert(mesh.geometry.getAttribute('anFxHydrology'));freed++;});const remove=installRoadHydrology(THREE,mesh);remove();remove();assert.equal(freed,1);assert.equal(mesh.geometry.getAttribute('anFxHydrology'),undefined);});

test('retiring a renderer evicts borrowed GPU uploads without closing reusable CPU images',()=>{const calls=[],texture={isTexture:true,dispose(){calls.push('gpu');},image:{close(){assert.fail('shared image must stay readable');}}},root={traverse(fn){fn({material:{map:texture}});}};snapshotSceneResources(root,{borrowedRoots:[root],disposeBorrowedGpu:true}).dispose();assert.deepEqual(calls,['gpu']);});

import {createAdvancedMaterials} from '../src/render/advanced-materials.mjs?v=633f841891fff528';
test('curvature cleanup frees its GPU attribute before restoring authored geometry',()=>{const root=new THREE.Group(),geometry=new THREE.BoxGeometry(1,1,1),material=new THREE.MeshStandardMaterial({name:'Steel',metalness:.9});root.add(new THREE.Mesh(geometry,material));const controller=createAdvancedMaterials(THREE,{root,scope:'workshop'});const added=Object.keys(geometry.attributes).filter(x=>!['position','normal','uv'].includes(x));assert(added.length>0);let observed=0;geometry.addEventListener('dispose',()=>{assert(geometry.getAttribute(added[0]));observed++;});controller.dispose();assert.equal(observed,1);assert.equal(geometry.getAttribute(added[0]),undefined);});
