import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {gunzipSync} from 'node:zlib';
import {preparePrograms} from '../src/render/shader-preparation.mjs?v=528cb164c75c6707';
import {createCockpitMirrors} from '../src/render/cockpit-mirrors.mjs?v=382a34eb1e53ae1f';
const payload=JSON.parse(readFileSync(new URL('../assets/manifests/workshop-bootstrap.json?v=71e24e64d3ef5ec5',import.meta.url)));
const T=await import('data:text/javascript;base64,'+gunzipSync(Buffer.from(payload.threeCoreGz,'base64')).toString('base64'));
function fixture(){let target=null;const calls=[];return {calls,info:{programs:[],autoReset:true},shadowMap:{enabled:true,type:2,autoUpdate:true,needsUpdate:true},autoClear:true,toneMapping:4,outputColorSpace:'srgb',clippingPlanes:[],localClippingEnabled:false,getContext:()=>({isContextLost:()=>false}),getRenderTarget:()=>target,setRenderTarget:t=>{target=t;},getActiveCubeFace:()=>0,getActiveMipmapLevel:()=>0,render(scene){assert.equal(scene.children.length,0);assert.equal(this.autoClear,false);},compile(view,camera,scene){const nodes=[],lights=[];view.traverse(n=>nodes.push(n));scene.traverseVisible(n=>lights.push(n));calls.push({nodes,lights,camera,clip:this.clippingPlanes});}};}
test('shader preparation snapshots hidden masks and yields in bounded batches, restoring renderer state',async()=>{const scene=new T.Scene(),camera=new T.PerspectiveCamera(),root=new T.Group(),light=new T.PointLight();scene.add(root,light);for(let i=0;i<35;i++)root.add(new T.Mesh(new T.BufferGeometry(),new T.MeshStandardMaterial()));const r=fixture(),plane=new T.Plane();r.clippingPlanes=[plane];const pending=preparePrograms(r,scene,camera);root.visible=false;light.visible=false;camera.layers.set(4);r.clippingPlanes=[];await pending;assert.equal(r.calls.reduce((n,c)=>n+c.nodes.length,0),35);assert(r.calls.every(c=>c.nodes.length<=8&&c.lights.length===1&&c.camera.layers.mask===1&&c.clip[0]!==plane&&c.clip[0].equals(plane)));assert.equal(r.autoClear,true);assert.equal(r.shadowMap.needsUpdate,true);assert.deepEqual(r.clippingPlanes,[]);assert.equal(r.getRenderTarget(),null);});
test('abort during shader submission restores state and stops future batches',async()=>{const c=new AbortController(),scene=new T.Scene(),camera=new T.Camera(),r=fixture();for(let i=0;i<50;i++)scene.add(new T.Mesh());const compile=r.compile;r.compile=function(...args){compile.apply(this,args);c.abort();};await assert.rejects(preparePrograms(r,scene,camera,scene,{signal:c.signal}),{name:'AbortError'});assert.equal(r.calls.length,1);assert.equal(r.autoClear,true);assert.equal(r.shadowMap.autoUpdate,true);});

test('projected spot-light maps survive pass snapshot and resource invalidation aborts later batches',async()=>{const scene=new T.Scene(),camera=new T.Camera(),r=fixture(),light=new T.SpotLight();light.map=new T.Texture();light.castShadow=true;scene.add(light);for(let i=0;i<35;i++)scene.add(new T.Mesh());const original=r.compile;r.compile=function(...args){original.apply(this,args);assert.equal(r.calls.at(-1).lights[0].map,light.map);scene.children[1].geometry.dispose();};await assert.rejects(preparePrograms(r,scene,camera),{name:'AbortError'});assert.equal(r.calls.length,1);});
test('a partial viewport and scissor survive every preparation batch',async()=>{const r=fixture(),scene=new T.Scene(),camera=new T.Camera();scene.add(new T.Mesh());let viewport=new T.Vector4(12,20,180,90),scissor=new T.Vector4(14,22,80,45),scissorTest=true;const initialViewport=viewport.clone(),initialScissor=scissor.clone();r.getViewport=v=>v.copy(viewport);r.setViewport=v=>viewport.copy(v);r.getScissor=v=>v.copy(scissor);r.setScissor=v=>scissor.copy(v);r.getScissorTest=()=>scissorTest;r.setScissorTest=v=>{scissorTest=v;};const setTarget=r.setRenderTarget;r.setRenderTarget=t=>{setTarget(t);viewport.set(0,0,1024,1024);scissor.set(0,0,1024,1024);scissorTest=false;};await preparePrograms(r,scene,camera);assert(viewport.equals(initialViewport));assert(scissor.equals(initialScissor));assert.equal(scissorTest,true);});

test('retired destination target aborts preparation instead of recreating its GPU resources',async()=>{const r=fixture(),scene=new T.Scene(),camera=new T.Camera(),target=new T.WebGLRenderTarget(32,32);r.setRenderTarget(target);for(let i=0;i<35;i++)scene.add(new T.Mesh());const compile=r.compile;r.compile=function(...args){compile.apply(this,args);target.dispose();};await assert.rejects(preparePrograms(r,scene,camera),{name:'AbortError'});assert.equal(r.calls.length,1);});

test('synchronous disposal before the producer microtask cannot resurrect shader resources',async()=>{const r=fixture(),scene=new T.Scene(),camera=new T.Camera(),mesh=new T.Mesh();scene.add(mesh);const pending=preparePrograms(r,scene,camera);mesh.geometry.dispose();await assert.rejects(pending,{name:'AbortError'});assert.equal(r.calls.length,0);assert.equal(mesh.geometry._listeners?.dispose?.length||0,0);});
