import test from 'node:test';
import assert from 'node:assert/strict';
import {readHalfFloatTarget} from '../src/render/async-probe-readback.mjs?v=15602b3ab72b0ac3';
function fixture(statuses=[1]){const calls=[],gl={PIXEL_PACK_BUFFER:2,PIXEL_PACK_BUFFER_BINDING:3,STREAM_READ:4,RGBA:5,HALF_FLOAT:6,SYNC_GPU_COMMANDS_COMPLETE:7,WAIT_FAILED:-1,TIMEOUT_EXPIRED:0,ALREADY_SIGNALED:1,CONDITION_SATISFIED:2,getParameter:()=>null,createBuffer:()=>({}),bindBuffer:(...x)=>calls.push(['bind',...x]),bufferData(){},readPixels(){calls.push(['read']);},fenceSync:()=>({}),flush(){},clientWaitSync:()=>statuses.shift()??0,getBufferSubData:(t,o,out)=>out.fill(1),deleteBuffer:()=>calls.push(['delete-buffer']),deleteSync:()=>calls.push(['delete-sync']),isContextLost:()=>false};let target='screen';const renderer={getContext:()=>gl,getRenderTarget:()=>target,getActiveCubeFace:()=>0,getActiveMipmapLevel:()=>0,setRenderTarget:x=>{target=x;}};return{gl,calls,renderer,target:()=>target};}
test('probe readback restores renderer before yielding and retires GPU fence/buffer',async()=>{const f=fixture([0,1]),out=new Uint16Array(4);await readHalfFloatTarget(f.renderer,{width:1,height:1},out,{wait:async()=>assert.equal(f.target(),'screen')});assert.deepEqual([...out],[1,1,1,1]);assert.equal(f.calls.filter(c=>c[0]==='delete-buffer').length,1);assert.equal(f.calls.filter(c=>c[0]==='delete-sync').length,1);});
test('cancel and timeout retire readback objects without calling getBufferSubData',async()=>{for(const timeout of [false,true]){const f=fixture([0]),abort=new AbortController();let reads=0;f.gl.getBufferSubData=()=>reads++;const request=readHalfFloatTarget(f.renderer,{width:1,height:1},new Uint16Array(4),{signal:abort.signal,timeoutMs:timeout?5:100,wait:()=>new Promise(()=>{})});if(!timeout)setImmediate(()=>abort.abort());await assert.rejects(request,{name:timeout?'TimeoutError':'AbortError'});assert.equal(reads,0);assert.equal(f.calls.filter(c=>c[0]==='delete-buffer').length,1);assert.equal(f.calls.filter(c=>c[0]==='delete-sync').length,1);}});
test('lost context and failed GPU fence settle without leaks',async()=>{for(const lost of [false,true]){const f=fixture([-1]);f.gl.isContextLost=()=>lost;await assert.rejects(readHalfFloatTarget(f.renderer,{width:1,height:1},new Uint16Array(4),{wait:async()=>{}}),/WebGL|GPU/);assert.equal(f.calls.filter(c=>c[0]==='delete-buffer').length,1);}});

test('readback restores a partial viewport and scissor before any asynchronous fence check',async()=>{const f=fixture([0,1]),current={viewport:[3,4,30,40],scissor:[5,6,7,8],physical:[9,10,11,12],test:true},copy=(out,values)=>{[out.x,out.y,out.z,out.w]=values;return out;};Object.assign(f.renderer,{getViewport:out=>copy(out,current.viewport),getScissor:out=>copy(out,current.scissor),getCurrentViewport:out=>copy(out,current.physical),getScissorTest:()=>current.test,setViewport:v=>current.viewport=[v.x,v.y,v.z,v.w],setScissor:v=>current.scissor=[v.x,v.y,v.z,v.w],setScissorTest:v=>current.test=v,state:{viewport:v=>current.physical=[v.x,v.y,v.z,v.w]}});const set=f.renderer.setRenderTarget;f.renderer.setRenderTarget=value=>{set(value);current.viewport=[0,0,1,1];current.scissor=[0,0,1,1];current.test=false;current.physical=[0,0,1,1];};const expected=structuredClone(current);await readHalfFloatTarget(f.renderer,{width:1,height:1},new Uint16Array(4),{wait:async()=>assert.deepEqual(current,expected)});assert.deepEqual(current,expected);});

import {withRenderTarget} from '../src/render/render-target-scope.mjs?v=30b8f30c25afc698';
test('async shader preparation never holds the cube render target while its promise is pending',async()=>{const f=fixture();let resolve;const preparation=new Promise(r=>resolve=r);const result=withRenderTarget(f.renderer,'cube',()=>{assert.equal(f.target(),'cube');return preparation;});assert.equal(f.target(),'screen');resolve('ready');assert.equal(await result,'ready');});
