import test from 'node:test';import assert from 'node:assert/strict';
import {runCooperatively} from '../src/runtime/cooperative-work.mjs?v=529f3ae5a1f59485';
import {THREE} from './cinematic-three.mjs?v=1538801f0545ceb6';
import {refineTerrainSurface,refineTerrainSurfaceAsync} from '../src/tracks/visuals/terrain-refinement.mjs?v=de6f345de5b7537a';
test('cooperative work yields and cancellation runs generator cleanup',async()=>{let t=0,yields=0,closed=false;const abort=new AbortController();function* work(){try{for(let i=0;i<100;i++)yield i;}finally{closed=true;}}await assert.rejects(runCooperatively(work(),{signal:abort.signal,now:()=>++t,yieldTask:async()=>{if(++yields===2)abort.abort(new DOMException('cancel','AbortError'));}}),{name:'AbortError'});assert(closed);assert.equal(yields,2);});
test('cooperative terrain preserves exact positions, normals and original geometry ownership',async()=>{const g=new THREE.PlaneGeometry(100,100,16,16);g.rotateX(-Math.PI/2);const a=new THREE.Mesh(g.clone()),b=new THREE.Mesh(g.clone());const options={roadField:()=>({distanceM:200,widthM:8}),maxTriangles:2000,targetEdgeM:20,nearEdgeM:20};const x=refineTerrainSurface(THREE,a,options),y=await refineTerrainSurfaceAsync(THREE,b,options);assert.deepEqual(x,y);assert.deepEqual(a.geometry.attributes.position.array,b.geometry.attributes.position.array);assert.deepEqual(a.geometry.attributes.normal.array,b.geometry.attributes.normal.array);assert.deepEqual(a.geometry.index.array,b.geometry.index.array);});

import {closeTerrainEdges,closeTerrainEdgesAsync} from '../src/tracks/visuals/terrain-edge-closure.mjs?v=bbcaf888f5341bdb';
test('cooperative terrain skirts preserve the complete visual mesh',async()=>{const geometry=new THREE.PlaneGeometry(200,150,4,4);geometry.rotateX(-Math.PI/2);geometry.translate(1000,100,1000);const material=new THREE.MeshStandardMaterial();const a=new THREE.Mesh(geometry.clone(),material),b=new THREE.Mesh(geometry.clone(),material);const query={project:([x,y,z])=>({position:[0,10,z],distanceXZ:Math.abs(x),widthM:8})};const options={query,floorY:-50,talus:true};assert.deepEqual(await closeTerrainEdgesAsync(THREE,b,options),closeTerrainEdges(THREE,a,options));assert.equal(a.children.length,1);for(const key of ['position','normal','uv'])assert.deepEqual(a.children[0].geometry.attributes[key].array,b.children[0].geometry.attributes[key].array);assert.deepEqual(a.children[0].geometry.index.array,b.children[0].geometry.index.array);});

import {findWaterfallImpact,findWaterfallImpactAsync} from '../src/tracks/visuals/waterfall-impact.mjs?v=af6a785cb4f89fac';
test('cooperative waterfall contacts preserve exact basin intersections',async()=>{const fall=new THREE.Mesh(new THREE.PlaneGeometry(15,30,10,10));fall.position.y=10;fall.updateMatrixWorld();const river=new THREE.Mesh(new THREE.PlaneGeometry(80,80,10,10));river.rotation.x=-Math.PI/2;river.name='basin';river.updateMatrixWorld();const result=findWaterfallImpact(THREE,fall,[river]);assert(result.impactSpanM>0);assert.deepEqual(await findWaterfallImpactAsync(THREE,fall,[river]),result);});

import {waterfallCameraProfile,waterfallCameraProfileAsync} from '../src/tracks/visuals/regional-waterfall-camera.mjs?v=a6f223041b3110de';
test('yielding camera sightline search preserves the exact authored photographic pose',async()=>{const root=new THREE.Group(),falls=[];for(let i=0;i<8;i++){const m=new THREE.Mesh(new THREE.PlaneGeometry(35,80),new THREE.MeshBasicMaterial());m.name='Fall_'+i;m.position.set(0,40,i*30);falls.push(m);root.add(m);}const query={project:p=>({sM:p[2]}),sample:s=>({position:[450,0,s],frame:{left:[1,0,0]}})},options={query,falls,heightAt:()=>0};assert.deepEqual(await waterfallCameraProfileAsync(THREE,root,options),waterfallCameraProfile(THREE,root,options));});
