import test from 'node:test';import assert from 'node:assert/strict';import {matrixCases,summarizeIntervals,validateRun} from './performance-matrix-core.mjs?v=470665282579cded';
test('combined matrix covers every selectable pair, both policies and five repetitions',()=>{const cases=matrixCases();assert.equal(cases.length,250);assert.equal(new Set(cases.map(c=>c.id)).size,250);assert.ok(cases.every(c=>c.durationSeconds===60));assert.ok(!cases.some(c=>c.vehicleId==='falcon'));for(const c of cases){const paired=cases.find(p=>p.trackId===c.trackId&&p.vehicleId===c.vehicleId&&p.repeat===c.repeat&&p.policy!==c.policy);assert.equal(paired.skyId,c.skyId);assert.equal(paired.weather,c.weather);}assert.throws(()=>matrixCases({durationSeconds:59}),/60/);});
test('frame statistics retain hitches and report observed cadence',()=>{const s=summarizeIntervals([10,10,10,10,200]);assert.equal(s.p95Ms,200);assert.equal(s.hitchesOver100Ms,1);assert.ok(Math.abs(s.meanFps-20.833333)<.001);});
function validResult(policy='high-fixed'){
 const c=matrixCases().find(c=>c.policy===policy&&c.repeat===4);
 return {case:c,measurement:{elapsedMs:60100,presentedIntervals:Array(100).fill(16),statuses:['RUNNING'],finalStatus:'RUNNING',progressM:500,recoveries:0,cameras:c.cameras,physicsWindowStart:{frameCount:0,totalSubsteps:0,overruns:0},physics:{frameCount:3500,totalSubsteps:7000,overruns:0},samples:Array.from({length:60},(_,i)=>({atMs:i*1000+300,tier:'high',requestedTier:'high',scale:1,adaptive:policy==='adaptive',trackId:c.trackId,vehicleId:c.vehicleId,skyId:c.skyId,weather:c.weather,camera:c.cameras[Math.floor(i/15)]}))}};
}
test('valid observed coverage passes for fixed and adaptive policies',()=>{assert.deepEqual(validateRun(validResult()),[]);assert.deepEqual(validateRun(validResult('adaptive')),[]);});
test('environment and adaptive settings are validated from samples',()=>{const r=validResult('adaptive');for(const s of r.measurement.samples){s.skyId='clear';s.weather='clear';s.adaptive=false;}const failures=validateRun(r);assert.ok(failures.includes('wrong-sky-or-weather'));assert.ok(failures.includes('adaptive-policy-disabled'));});
test('camera commands cannot substitute for observed camera segments',()=>{const r=validResult();r.measurement.samples.forEach(s=>s.camera='cockpit');assert.ok(validateRun(r).includes('camera-coverage'));});
test('camera segment must match elapsed time, not just contain every camera',()=>{const r=validResult();r.measurement.samples.forEach(s=>s.camera=r.case.cameras[(Math.floor(s.atMs/15000)+1)%4]);assert.ok(validateRun(r).includes('camera-coverage'));});
test('empty samples, nonfinite durations and progress, and invalid frame intervals are rejected',()=>{for(const [mutate,reason] of [[r=>r.measurement.samples=[],'samples-missing'],[r=>r.measurement.elapsedMs=NaN,'duration-invalid'],[r=>r.measurement.progressM=NaN,'progress-invalid'],[r=>r.measurement.presentedIntervals[0]=-1,'presented-intervals-invalid'],[r=>r.measurement.samples[0].atMs=NaN,'sample-time-invalid']]){const r=validResult();mutate(r);assert.ok(validateRun(r).includes(reason),reason);}});
test('physics counters must start at zero for each measurement window',()=>{const r=validResult();r.measurement.physicsWindowStart.frameCount=4298;assert.ok(validateRun(r).includes('physics-window-not-reset'));});
test('pending quality requests exceeding 30 seconds cannot silently pass',()=>{const r=validResult('adaptive');for(const s of r.measurement.samples.filter(s=>s.atMs>20000)){s.requestedTier='balanced';s.transitionReason='p95-above-target-budget';}assert.ok(validateRun(r).includes('quality-transition-timeout'));r.measurement.samples.filter(s=>s.atMs>45000).forEach(s=>s.tier='balanced');assert.ok(!validateRun(r).includes('quality-transition-timeout'));});
test('fixed quality drift and paused simulation invalidate coverage',()=>{const r=validResult();r.measurement.samples[0].tier='low';assert.ok(validateRun(r).includes('fixed-quality-drift'));r.measurement.statuses.push('PAUSED');assert.ok(validateRun(r).includes('not-running'));});
test('resume environment comparison keeps stable hardware and browser version',async()=>{const {benchmarkEnvironment}=await import('./performance-matrix-core.mjs?v=470665282579cded');const info={modelName:'host',gpu:{devices:[{vendorId:1,deviceId:2,driverVersion:'v1'}],auxAttributes:{glRenderer:'GPU',glVersion:'GL',processCrashCount:0}}};const version={product:'Chrome/1',jsVersion:'v8/1'};const host={platform:'win32',arch:'x64',release:'build',cpuModels:['CPU'],totalMemoryBytes:16};const baseline=benchmarkEnvironment(info,version,host);info.gpu.auxAttributes.processCrashCount=3;assert.deepEqual(benchmarkEnvironment(info,version,host),baseline);info.gpu.devices[0].deviceId=3;assert.notDeepEqual(benchmarkEnvironment(info,version,host),baseline);assert.notDeepEqual(benchmarkEnvironment(info,{...version,product:'Chrome/2'},host),baseline);});
test('Node watchdog terminates an unresolved phase and invokes browser cleanup',async()=>{const {withWatchdog}=await import('./performance-matrix-watchdog.mjs?v=c378812c5ee5c044');let terminated=0;const start=Date.now();await assert.rejects(withWatchdog('renderer-hung',25,()=>new Promise(()=>{}),()=>{terminated++;return new Promise(()=>{});}),error=>error.code==='BENCHMARK_PHASE_TIMEOUT'&&error.phase==='renderer-hung');assert.equal(terminated,1);assert.ok(Date.now()-start<1000);assert.equal(await withWatchdog('quick',1000,()=>42),42);});
