import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {startServer} from '../server.mjs';
let playwright;try{playwright=createRequire(import.meta.url)('playwright');}catch{playwright=createRequire(process.env.PLAYWRIGHT_PACKAGE_JSON||'C:/Users/Gaston/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json')('playwright');}const {chromium}=playwright;
const label=process.argv[2]||'verified',root=process.argv[3]||path.resolve(import.meta.dirname,'..');const output=process.env.PHOTOREAL_REPORT_DIR||path.resolve(import.meta.dirname,'../../Reports/Asfalto_Nacional_v8/photoreal-2026-10-04');await fs.mkdir(output,{recursive:true});
const report={label,checks:[],errors:[],consoleErrors:[],externalRequests:[],measurements:[],environments:[]};const check=(name,value)=>{assert.ok(value,name);report.checks.push(name);console.log(name);};
const server=await startServer({root}),browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=d3d11']});report.environment={browser:browser.version(),angle:'D3D11',headless:true,viewport:[1280,800],fixedRenderTier:'high',advancedQuality:'balanced',cadence:'60Hz rAF; not a device certification'};
try{
 const page=await browser.newPage({viewport:{width:1280,height:800}});page.setDefaultTimeout(180000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(server.url))report.externalRequests.push(r.url());});
 const shot=async name=>page.screenshot({path:output+'/'+label+'-'+name+'.png'});
 const frameWait=n=>page.evaluate(async n=>{for(let i=0;i<n;i++)await new Promise(requestAnimationFrame);},n);
 const ready=()=>page.waitForFunction(()=>{const d=__cockpit.v7RenderDiagnostics();return d.preparation.renderingPending===0&&!d.preparation.batch?.pending&&(!d.preparation.tier||d.preparation.tier.phase==='ready');});
 async function measure(name){await ready();await frameWait(60);await page.evaluate(()=>__cockpit.v7BeginMeasurement());const m=await page.evaluate(async name=>{const intervals=[];let previous=await new Promise(requestAnimationFrame);for(let i=0;i<300;i++){const now=await new Promise(requestAnimationFrame);intervals.push(now-previous);previous=now;}intervals.sort((a,b)=>a-b);return{name,p50:intervals[149],p95:intervals[284],p99:intervals[296],max:intervals.at(-1),render:__cockpit.v7RenderDiagnostics(),graphics:__cockpit.advancedGraphicsDiagnostics(),contact:__cockpit.raceWorld.getV6Diagnostics().vehicleContactOcclusion,state:__cockpit.raceGetState()};},name);report.measurements.push(m);console.log(JSON.stringify({name,p50:m.p50,p95:m.p95,p99:m.p99,gpu:m.render.gpu}));return m;}
 await page.goto(server.url+'?qa=1');await page.waitForFunction(()=>globalThis.__chevyV6Complete?.workshop?.loaded&&document.querySelector('#loading').hidden);await page.waitForFunction(()=>__chevyV6Complete.workshop.advancedGraphics?.diagnostics().preparation.ready);check('taller listo',true);await shot('workshop');
 await page.locator('[data-v6-panel=drive]').click();await page.locator('[data-an-mode=drive]').click();await page.locator('#v6-drive-start').click();await page.waitForFunction(()=>globalThis.__cockpit?.ready&&__cockpit.raceWorld?.state.status==='RUNNING');await page.evaluate(()=>__cockpit.debugSetPerformanceAdaptive(false));await ready();
 await measure('standing-clear');await shot('cockpit');
 await page.evaluate(()=>__cockpit.raceSetCamera('chase'));await ready();await shot('chase');await page.evaluate(()=>__cockpit.setGear(1));await page.keyboard.down('w');await frameWait(180);await page.keyboard.up('w');const moving=await measure('driving-clear');await shot('driving');check('conducción con input real conserva avance',moving.state.raceProgress-report.measurements[0].state.raceProgress>1&&moving.state.speedMps>0.1);
 if(label==='verified'){
  check('capacidad WebGPU distingue adaptador del backend',moving.graphics.capabilities.backend==='webgl2'&&moving.graphics.capabilities.webgpu.rendererCompatible===false);check('AA y mip filtering activos en Equilibrado',moving.graphics.antialias.enabled&&moving.graphics.filtering.borrowedTextures>0);check('apoyo visual sigue contactos reales con un dibujo',moving.contact.patches>=4&&moving.contact.triangles<=10&&moving.contact.steadyDrawCalls===1);
  await page.keyboard.press('Escape');check('pausa disponible',await page.evaluate(()=>__asfaltoRacePresentation.isOpen()));await page.keyboard.press('Escape');await page.evaluate(()=>__cockpit.raceSetCamera('cockpit'));
  for(const skyId of ['overcast','golden-hour','sunset','moonrise','night','clear']){await page.evaluate(async skyId=>{await __cockpit.raceSetSettings({skyId});},skyId);await ready();await frameWait(30);await shot(skyId);const d=await page.evaluate(()=>({environment:__cockpit.raceWorld.getAdvancedGraphicsEnvironment(),aa:__cockpit.advancedGraphicsDiagnostics().antialias,fault:__cockpit.runtimeFailureDiagnostics().fault}));check('HDRI '+skyId+' usable',!d.fault&&d.aa.targets===1);report.environments.push({skyId,...d});}
  for(const weather of ['rain','fog','clear']){await page.evaluate(async weather=>{await __cockpit.raceSetSettings({weather});},weather);await ready();await frameWait(30);await shot(weather);const d=await page.evaluate(()=>({environment:__cockpit.raceWorld.getAdvancedGraphicsEnvironment(),aa:__cockpit.advancedGraphicsDiagnostics().antialias,fault:__cockpit.runtimeFailureDiagnostics().fault}));check('clima '+weather+' usable',!d.fault&&d.aa.targets===1);report.environments.push({weather,...d});}
  const resourcesBefore=await page.evaluate(()=>__cockpit.v7RenderDiagnostics().resources);await page.evaluate(()=>{for(let i=0;i<20;i++){__asfaltoAdvancedGraphics.setMode('off');__asfaltoAdvancedGraphics.setMode('balanced');}});await ready();await frameWait(60);const resourcesAfter=await page.evaluate(()=>__cockpit.v7RenderDiagnostics().resources);report.cycles={resourcesBefore,resourcesAfter};check('20 cambios no acumulan targets',resourcesAfter.textures<=resourcesBefore.textures+1&&resourcesAfter.geometries<=resourcesBefore.geometries+1);
  await page.setViewportSize({width:844,height:390});await ready();await frameWait(30);await shot('landscape');check('resize renderiza y ajusta target',await page.evaluate(()=>__cockpit.advancedGraphicsDiagnostics().antialias.size?.every(n=>n>0)));
  await page.emulateMedia({reducedMotion:'reduce'});await page.keyboard.press('Escape');check('pausa y foco con movimiento reducido',await page.locator('[data-pause-action=resume]').evaluate(n=>n===document.activeElement));await page.keyboard.press('Escape');await page.setViewportSize({width:1280,height:800});
  await page.evaluate(()=>__asfaltoAdvancedGraphics.setMode('low'));await ready();check('Bajo libera AA y conserva carrera',await page.evaluate(()=>__cockpit.advancedGraphicsDiagnostics().antialias.targets===0&&__cockpit.raceGetState().status==='RUNNING'));await page.evaluate(()=>__asfaltoAdvancedGraphics.setMode('balanced'));await ready();await page.keyboard.press('Escape');await page.locator('[data-pause-action=workshop]').click();await page.waitForFunction(()=>__chevyV6Complete.workshop.active&&document.body.classList.contains('v6-menu-open'));await page.waitForFunction(()=>__chevyV6Complete.workshop.advancedGraphics.diagnostics().preparation.ready);await shot('returned-workshop');check('retorno al taller restaura render y menú',await page.evaluate(()=>__chevyV6Complete.workshop.advancedGraphics.diagnostics().antialias.targets===1));
 }
 check('sin errores JS',report.errors.length===0);check('sin errores de shader/WebGL',report.consoleErrors.length===0);check('sin peticiones externas',report.externalRequests.length===0);
}finally{await fs.writeFile(output+'/'+label+'-browser.json',JSON.stringify(report,null,2));await browser.close();await server.close();}
