import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const storageCode=fs.readFileSync(new URL('../src/runtime/versioned-storage.js?v=51824c85cd5afb1d',import.meta.url),'utf8');
const key='chevy-serie2-v6-profile',prefix='asfalto:v7:';
function boot(seed={},denyProfile=false){const data=new Map(Object.entries(seed));const localStorage={get length(){return data.size},key:i=>[...data.keys()][i],getItem:k=>data.get(k)??null,setItem:(k,v)=>{if(denyProfile&&k===prefix+key)throw new Error('Quota exceeded');data.set(k,String(v));},removeItem:k=>data.delete(k)};const context={localStorage};vm.runInNewContext(storageCode,context);return{storage:context.__asfaltoV7Storage,data};}
test('new storage and zero balance remain unchanged',async()=>{const a=boot();await a.storage.ready;assert.equal(a.storage.getItem(key),null);const b=boot({[key]:JSON.stringify({workshopTokens:0,unknown:42})});await b.storage.ready;assert.equal(JSON.parse(b.storage.getItem(key)).workshopTokens,0);assert.equal(JSON.parse(b.storage.getItem(key)).unknown,42);});
test('v7 only and identical profiles do not prompt',async()=>{for(const seed of [{[prefix+key]:'{"workshopTokens":25}'},{[prefix+key]:'{"workshopTokens":25}',[key]:'{"workshopTokens":25}'}]){const {storage}=boot(seed);await storage.ready;assert.equal(storage.diagnostics().profileChoicePending,false);assert.equal(JSON.parse(storage.getItem(key)).workshopTokens,25);}});
test('divergent profiles require a choice and preserve exact snapshots',async()=>{for(const choice of ['v7','v8']){const v7=JSON.stringify({workshopTokens:25,motorsportV7:{runs:{old:1}},unknown:'a'}),v8=JSON.stringify({workshopTokens:83,unknown:'b'});const {storage,data}=boot({[prefix+key]:v7,[key]:v8,[prefix+'@migration-v1']:'complete'});assert.equal(storage.diagnostics().profileChoicePending,true);let ready=false;storage.ready.then(()=>ready=true);await Promise.resolve();assert.equal(ready,false);assert.equal(storage.chooseProfile(choice),true);await storage.ready;assert.equal(storage.getItem(key),choice==='v7'?v7:v8);assert.equal(storage.recoveryProfiles().v7,v7);assert.equal(storage.recoveryProfiles().v8,v8);assert.equal(data.get(key),v8);const again=boot(Object.fromEntries(data));await again.storage.ready;assert.equal(again.storage.getItem(key),choice==='v7'?v7:v8);assert.equal(again.storage.diagnostics().profileChoicePending,false);}});
test('v8 only migrates even with old copy marker',async()=>{const {storage}=boot({[key]:'{"workshopTokens":0}',[prefix+'@migration-v1']:'complete'});await storage.ready;assert.equal(JSON.parse(storage.getItem(key)).workshopTokens,0);});
test('overlapping intro and loading restore inert only after both release',()=>{const context={};vm.runInNewContext(fs.readFileSync(new URL('../src/runtime/modal-inert.js?v=130a2433cdd96837',import.meta.url),'utf8'),context);for(const reverse of [false,true]){const menu={inert:false},already={inert:true};const intro=context.__asfaltoModalInert.acquire([menu,already]);const loading=context.__asfaltoModalInert.acquire([menu,already]);const releases=reverse?[loading,intro]:[intro,loading];releases[0]();assert.equal(menu.inert,true);releases[1]();assert.equal(menu.inert,false);assert.equal(already.inert,true);releases[0]();assert.equal(menu.inert,false);}});

test('failed profile copy cannot mark recovery complete or load defaults',async()=>{const {storage,data}=boot({[key]:'{"workshopTokens":83}',[prefix+'@migration-v1']:'complete'},true);assert.equal(storage.diagnostics().profileChoicePending,true);let ready=false;storage.ready.then(()=>ready=true);await Promise.resolve();assert.equal(ready,false);assert.equal(data.get('asfalto:recovery:v8-v7:complete'),undefined);assert.throws(()=>storage.chooseProfile('v8'),/Quota/);assert.equal(data.get(key),'{"workshopTokens":83}');assert.equal(data.get('asfalto:recovery:v8-v7:complete'),undefined);});

test('Iguazu shipping assets satisfy restored locked adapter',async()=>{const {createHash}=await import('node:crypto');const source=fs.readFileSync(new URL('../src/tracks/adapters/cataratas-iguazu.mjs?v=1826a1f0c1dfbf5f',import.meta.url),'utf8');const locks=JSON.parse(source.match(/const LOCKS=Object.freeze\((.+)\);/)[1]);const manifest=JSON.parse(source.match(/const MANIFEST=Object.freeze\((.+)\);/)[1]);assert.deepEqual(JSON.parse(fs.readFileSync(new URL('../tracks/cataratas-iguazu/manifest.json?v=a4c8b64670fdf0e1',import.meta.url))),manifest);for(const [file,lock] of [['manifest.json',locks.manifest],['route.json',locks.route],['scene.glb',locks.visual['./scene.glb']],['collision.glb',locks.collision['./collision.glb']]]){const bytes=fs.readFileSync(new URL('../tracks/cataratas-iguazu/'+file,import.meta.url));assert.equal(bytes.length,lock.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex').toUpperCase(),lock.sha256);}});
