import test from 'node:test';import assert from 'node:assert/strict';import {getRenderHost} from '../src/runtime/render-host.mjs?v=59a89ed6c25fba10';
class Vector{constructor(x=0,y=0,z=0,w=0){Object.assign(this,{x,y,z,w});}clone(){return new Vector().copy(this);}copy(v){Object.assign(this,v);return this;}multiplyScalar(n){this.x*=n;this.y*=n;return this;}floor(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this;}}
class Color{constructor(value=0){this.value=value;}clone(){return new Color(this.value);}copy(v){this.value=v.value;return this;}}
function fixture(compile=()=>Promise.resolve()){const events={},canvas={dataset:{},classList:{remove(){}},addEventListener:(k,v)=>events[k]=v,removeEventListener:k=>delete events[k]},calls=[];let color=new Color(),alpha=1,size=new Vector(200,100),dpr=1,target=null,face=0,mip=0,viewport=new Vector(0,0,200,100),scissor=viewport.clone(),test=false,physical=viewport.clone(),disposed=0;
 const raw={domElement:canvas,shadowMap:{enabled:true,type:1,autoUpdate:true,needsUpdate:false},xr:{enabled:false},info:{autoReset:true,render:{},memory:{}},state:{viewport:v=>physical=v.clone()},toneMappingExposure:1,autoClear:true,clippingPlanes:[],getContext:()=>({getContextAttributes:()=>({antialias:true})}),getClearColor:v=>v.copy(color),getClearAlpha:()=>alpha,setClearColor:(c,a=1)=>{color=c instanceof Color?c.clone():new Color(c);alpha=a;},getRenderTarget:()=>target,getActiveCubeFace:()=>face,getActiveMipmapLevel:()=>mip,setRenderTarget:(t,f=0,m=0)=>{target=t;face=f;mip=m;},getViewport:v=>v.copy(viewport),getCurrentViewport:v=>v.copy(physical),setViewport:v=>{viewport=v.clone();physical=v.clone();},getScissor:v=>v.copy(scissor),setScissor:v=>scissor=v.clone(),getScissorTest:()=>test,setScissorTest:v=>test=v,getSize:v=>v.copy(size),setSize:(x,y)=>{size=new Vector(x,y);calls.push('resize');},getPixelRatio:()=>dpr,setPixelRatio:v=>{dpr=v;calls.push('dpr');},render(){calls.push({target,exposure:this.toneMappingExposure,shadow:this.shadowMap.type});this.renderBufferDirect();},renderBufferDirect(){calls.push('draw');},compileAsync:compile,dispose:()=>disposed++};
 const T={Color,Vector2:Vector,Vector4:Vector,WebGLRenderTarget:class{dispose(){this.disposed=true;}}};const host=getRenderHost(T,{rendererFactory:()=>raw});return{host,raw,calls,events,disposed:()=>disposed};}
test('one context, inactive state/resize isolated, nested throw restores target face mip',()=>{const f=fixture(),a=f.host.acquireView('workshop'),b=f.host.acquireView('race');a.activate();a.renderer.toneMappingExposure=2;a.renderer.setRenderTarget({name:'a'},3,2);b.renderer.setSize(50,40);b.renderer.setPixelRatio(2);b.renderer.shadowMap.type=7;b.renderer.toneMappingExposure=3;assert.equal(f.raw.toneMappingExposure,2);assert.equal(f.raw.getSize(new Vector()).x,200);assert.throws(()=>b.withState(()=>{assert.equal(f.raw.toneMappingExposure,3);a.withState(()=>assert.equal(f.raw.toneMappingExposure,2));throw Error('expected');}),/expected/);assert.equal(f.raw.getActiveCubeFace(),3);assert.equal(f.raw.getActiveMipmapLevel(),2);assert.equal(f.raw.shadowMap.type,1);b.activate();assert.equal(f.raw.getPixelRatio(),2);assert.equal(f.raw.getSize(new Vector()).x,50);});
test('async continuation does not retain global state or draw over active canvas',async()=>{const f=fixture(),a=f.host.acquireView('workshop'),b=f.host.acquireView('race');a.activate();a.renderer.toneMappingExposure=2;b.renderer.toneMappingExposure=7;await b.withState(async()=>{await Promise.resolve();b.renderer.render();});assert.equal(f.raw.toneMappingExposure,2);const draw=f.calls.find(x=>typeof x==='object');assert.ok(draw.target);assert.equal(draw.exposure,7);});
test('raw internal dispatch uses only owner patch with correct this and restores',()=>{const f=fixture(),a=f.host.acquireView('workshop'),b=f.host.acquireView('race');a.activate();const original=b.renderer.renderBufferDirect;let patched=0;b.renderer.renderBufferDirect=function(...args){assert.equal(this,f.raw);patched++;return original(...args);};a.renderer.render();assert.equal(patched,0);b.renderer.render();assert.equal(patched,1);a.renderer.render();assert.equal(patched,1);});
test('lease disposal never disposes physical renderer; final shutdown waits native compile',async()=>{let settle;const f=fixture(()=>new Promise(r=>settle=r));const a=f.host.acquireView('workshop'),b=f.host.acquireView('race');a.activate();a.release();assert.equal(f.disposed(),0);b.activate();const compiling=b.renderer.compileAsync({traverse(){}});b.release();const shutting=f.host.shutdown();assert.equal(f.disposed(),0);settle();await compiling;await shutting;assert.equal(f.disposed(),1);});
test('context loss suspends frames and restore advances epoch without activate callback',()=>{const f=fixture();let restore=0;const a=f.host.acquireView('workshop',{onContextRestored:()=>restore++});a.activate();f.events.webglcontextlost({preventDefault(){}});assert.equal(a.frame(()=>true),false);assert.equal(f.host.diagnostics().contextEpoch,1);f.events.webglcontextrestored();assert.equal(restore,1);assert.equal(f.host.diagnostics().contextEpoch,2);});

test('restored Three internals are resolved dynamically by nested facades',()=>{const f=fixture(),a=f.host.acquireView('workshop');a.activate();const oldShadow=f.raw.shadowMap;let resets=0;f.raw.shadowMap={enabled:true,type:4,autoUpdate:true,needsUpdate:false};f.raw.info={autoReset:true,render:{newContext:true},reset(){assert.equal(this,f.raw.info);resets++;}};a.renderer.shadowMap.type=9;a.renderer.info.autoReset=false;a.renderer.info.reset();assert.equal(f.raw.shadowMap.type,9);assert.equal(oldShadow.type,1);assert.equal(f.raw.info.autoReset,false);assert.equal(a.renderer.info.render.newContext,true);assert.equal(resets,1);});
