import fs from 'node:fs/promises';import {gunzipSync} from 'node:zlib';import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {startServer} from '../server.mjs';
let playwright;try{playwright=createRequire(import.meta.url)('playwright');}catch{playwright=createRequire(process.env.PLAYWRIGHT_PACKAGE_JSON||'C:/Users/Gaston/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json')('playwright');}const {chromium}=playwright;
const root=new URL('../',import.meta.url);const out=process.env.PHOTOREAL_REPORT_DIR?new URL('file:///'+process.env.PHOTOREAL_REPORT_DIR.replaceAll('\\','/').replace(/\/$/,'')+'/'):new URL('../../Reports/Asfalto_Nacional_v8/photoreal-2026-10-04/',import.meta.url);await fs.mkdir(out,{recursive:true});
const payload=JSON.parse(await fs.readFile(new URL('assets/manifests/workshop-bootstrap.json',root)));const core='data:text/javascript;base64,'+gunzipSync(Buffer.from(payload.threeCoreGz,'base64')).toString('base64');const source=gunzipSync(Buffer.from(payload.threeModuleGz,'base64')).toString().replaceAll('./three.core.min.js',core);
const server=await startServer({root:import.meta.dirname+'/..'}),browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=d3d11']});
try{
 const page=await browser.newPage();await page.route('**/aa-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><body></body>'}));await page.goto(server.url+'aa-fixture');const errors=[],consoleMessages=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>consoleMessages.push(m.type()+': '+m.text()));
 const result=await page.evaluate(async source=>{
  const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));const T=await import(url);let createSpatialAntialias;try{({createSpatialAntialias}=await import('/src/render/spatial-antialias.mjs'));}catch{return {missing:true};}
  const r=new T.WebGLRenderer({antialias:false,preserveDrawingBuffer:true});r.setSize(64,64);r.setClearColor('black',1);r.outputColorSpace=T.SRGBColorSpace;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1;document.body.append(r.domElement);
  const scene=new T.Scene(),camera=new T.Camera(),geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute([-1,-1,0,1,-1,0,-1,.8,0],3));const material=new T.MeshBasicMaterial({color:'white'});const mesh=new T.Mesh(geometry,material);scene.add(mesh);
  const aa=createSpatialAntialias(T,{renderer:r,quality:'high',passCount:1});await aa.prepare(()=>r.compileAsync(scene,camera));
  const pixels=()=>{const gl=r.getContext(),data=new Uint8Array(64*64*4);gl.readPixels(0,0,64,64,gl.RGBA,gl.UNSIGNED_BYTE,data);return data;};
  r.render(scene,camera);const original=pixels();aa.render(()=>r.render(scene,camera));const filtered=pixels();
  const mids=p=>{let n=0;for(let i=0;i<p.length;i+=4)if(p[i]>5&&p[i]<original[0]-5)n++;return n;};
  const tests={diagonalFiltered:mids(filtered)>mids(original)+20};
  const {createVehicleContactOcclusion}=await import('/src/render/vehicle-contact-occlusion.mjs');const contactScene=new T.Scene(),topCamera=new T.OrthographicCamera(-3,3,3,-3,.1,10);topCamera.position.set(0,4,0);topCamera.up.set(0,0,-1);topCamera.lookAt(0,0,0);const floorGeometry=new T.PlaneGeometry(6,6),floorMaterial=new T.MeshBasicMaterial({color:'white',side:T.DoubleSide}),floor=new T.Mesh(floorGeometry,floorMaterial);floor.rotation.x=-Math.PI/2;contactScene.add(floor);r.render(contactScene,topCamera);const withoutContact=pixels();const contact=createVehicleContactOcclusion(T,{scene:contactScene,renderer:r});const {compileVisiblePass}=await import('/src/render/pass-preparation.mjs');await compileVisiblePass(r,contactScene,topCamera);tests.contactHiddenPrepared=!!r.properties.get(contact.mesh.material).currentProgram&&contact.mesh.visible===false;const support={chassis:{rotation:[0,0,0,1]},wheels:['frontLeft','frontRight','rearLeft','rearRight'].map((id,i)=>({id,contact:true,point:[i<2?1.4:-1.4,0,i%2?.72:-.72],normal:[0,1,0],surface:'asphalt'}))};contact.update(support);r.render(contactScene,topCamera);tests.contactSingleDraw=r.info.render.calls===2;const withContact=pixels();let darkened=0;for(let i=0;i<withContact.length;i+=4)if(withoutContact[i]-withContact[i]>5)darkened++;tests.contactSoftSupport=darkened>100;support.wheels.forEach(w=>w.contact=false);contact.update(support);r.render(contactScene,topCamera);const releasedContact=pixels();tests.contactLossRestoresFloor=releasedContact.every((v,i)=>v===withoutContact[i]);contact.dispose();floorGeometry.dispose();floorMaterial.dispose();
  const {createRaceColorGrade}=await import('/src/render/race-color-grade.mjs');const grade=createRaceColorGrade({THREE:T,renderer:r,samples:0,getQuality:()=> 'high'});await grade.setSettings({contrast:1.03});
  material.color.setRGB(4,2,1);grade.render(()=>r.render(scene,camera));const plainGrade=pixels();grade.render(()=>aa.render(()=>r.render(scene,camera)));const aaGrade=pixels();tests.gradingSingleToneMapping=Math.abs(plainGrade[400]-aaGrade[400])<3&&Math.abs(plainGrade[401]-aaGrade[401])<3;grade.dispose();
  const blueMaterial=new T.MeshBasicMaterial({color:'blue'}),blueGeometry=new T.PlaneGeometry(2,2),blueMesh=new T.Mesh(blueGeometry,blueMaterial);blueMesh.position.z=.8;
  aa.render(()=>{r.render(scene,camera);r.clearDepth();const interior=new T.Scene();interior.add(blueMesh);r.autoClear=false;r.render(interior,camera);});const interiorPixels=pixels();tests.independentInteriorDepth=interiorPixels[400]===0&&interiorPixels[402]>200;blueGeometry.dispose();blueMaterial.dispose();
  material.color.setRGB(4,2,1);aa.setQuality('off');aa.render(()=>r.render(scene,camera));const plainHdr=pixels();aa.setQuality('high');aa.render(()=>r.render(scene,camera));const filteredHdr=pixels();tests.singleToneMapping=Math.abs(plainHdr[4*100]-filteredHdr[4*100])<3;
  const target=new T.WebGLRenderTarget(64,64,{type:T.HalfFloatType});target.texture.colorSpace=T.LinearSRGBColorSpace;r.setRenderTarget(target);aa.render(()=>r.render(scene,camera));const hdr=new Uint16Array(4);r.readRenderTargetPixels(target,5,5,1,1,hdr);tests.hdrRetained=Math.abs(T.DataUtils.fromHalfFloat(hdr[0])-4)<.03&&Math.abs(T.DataUtils.fromHalfFloat(hdr[1])-2)<.03;
  r.setViewport(3,4,55,50);r.setScissor(1,2,57,59);r.setScissorTest(true);const viewport=r.getViewport(new T.Vector4()).toArray(),scissor=r.getScissor(new T.Vector4()).toArray();const auto=r.autoClear,info=r.info.autoReset;
  try{aa.render(()=>{r.setClearColor('red',.2);throw Error('draw failed');});}catch(error){tests.errorPreserved=error.message==='draw failed';}
  tests.stateRestored=r.getRenderTarget()===target&&r.getScissorTest()&&JSON.stringify(viewport)===JSON.stringify(r.getViewport(new T.Vector4()).toArray())&&JSON.stringify(scissor)===JSON.stringify(r.getScissor(new T.Vector4()).toArray())&&r.autoClear===auto&&r.info.autoReset===info;
  r.setRenderTarget(null);r.setViewport(0,0,64,64);r.setScissorTest(false);const textures=r.info.memory.textures;
  for(let i=0;i<20;i++){aa.setQuality('low');aa.render(()=>r.render(scene,camera));aa.setQuality('high');aa.render(()=>r.render(scene,camera));}tests.noTextureGrowth=r.info.memory.textures===textures;
  r.setSize(32,48);aa.render(()=>r.render(scene,camera));tests.resize=JSON.stringify(aa.diagnostics().size)==='[32,48]';

  const lose=r.getContext().getExtension('WEBGL_lose_context');let recovery={status:'unsupported',before:r.getContext().getError()};if(lose){
   const eventOnce=(type,timeout=8000)=>new Promise((resolve,reject)=>{const done=event=>{clearTimeout(timer);r.domElement.removeEventListener(type,done);event.preventDefault();resolve();};const timer=setTimeout(()=>{r.domElement.removeEventListener(type,done);reject(Error(type+' timeout'));},timeout);r.domElement.addEventListener(type,done);});
   r.domElement.addEventListener('webglcontextlost',()=>{geometry.dispose();material.dispose();target.dispose();},{once:true});const lost=eventOnce('webglcontextlost');lose.loseContext();await lost;
   // Recovery must be requested in a later task, after the loss event dispatch completes.
   await new Promise(resolve=>setTimeout(resolve,100));const restored=eventOnce('webglcontextrestored');lose.restoreContext();await restored;
   recovery.afterRestore=r.getContext().getError();tests.restoreInvalidates=aa.diagnostics().targets===0;r.render(scene,camera);recovery.plainRender=r.getContext().getError();aa.render(()=>r.render(scene,camera));recovery.filteredRender=r.getContext().getError();tests.actualContextRecovery=aa.diagnostics().targets===1&&recovery.afterRestore===0&&recovery.plainRender===0&&recovery.filteredRender===0;recovery.status='restored';
  }
  aa.setQuality('off');tests.offReleases=aa.diagnostics().targets===0;aa.setQuality('high');aa.dispose();aa.dispose();tests.disposeReleases=aa.diagnostics().disposed&&aa.diagnostics().targets===0;
  const phone=createSpatialAntialias(T,{renderer:r,phone:true,quality:'high'});phone.render(()=>r.render(scene,camera));tests.phoneFallback=phone.diagnostics().targets===0;phone.dispose();
  const limited=createSpatialAntialias(T,{renderer:r,quality:'high',hdrSupported:false});limited.render(()=>r.render(scene,camera));tests.noHdrFallback=limited.diagnostics().targets===0;limited.dispose();
  const glError=r.getContext().getError();target.dispose();geometry.dispose();material.dispose();r.dispose();URL.revokeObjectURL(url);return{missing:false,tests,glError,diagonal:{original:mids(original),filtered:mids(filtered)},hdr:Array.from(hdr).map(T.DataUtils.fromHalfFloat),recovery};
 },source);
 await fs.writeFile(new URL('aa-gpu.json',out),JSON.stringify({browser:browser.version(),errors,consoleMessages,result},null,2));assert.equal(result.missing,false,'spatial AA implementation missing');for(const [name,value]of Object.entries(result.tests))assert.ok(value,name);assert.equal(result.glError,0);assert.deepEqual(errors,[]);console.log(JSON.stringify(result,null,2));
}finally{await browser.close();await server.close();}
