import test from 'node:test';
import assert from 'node:assert/strict';
import {createRaceDrivingAudio} from '../src/audio/race-driving-audio.mjs';
import {createRaceSoundscape} from '../src/audio/race-soundscape.mjs?v=balance-20260917';
import {createV7InteractionSound} from '../src/audio/v7-interaction-sound.mjs';
class Parameter{value=0;setTargetAtTime(v){this.value=v;}setValueAtTime(v){this.value=v;}linearRampToValueAtTime(v){this.value=v;}exponentialRampToValueAtTime(v){this.value=v;}cancelScheduledValues(){}}
class Node{constructor(context){this.context=context;context.nodes.push(this);for(const key of ['gain','frequency','Q','pan','threshold','knee','ratio','attack','release'])this[key]=new Parameter();}connect(next){this.connected=true;return next;}disconnect(){this.connected=false;}start(){this.started=true;}stop(when=0){if(when>this.context.currentTime){this.stopAt=when;return;}this.stopped=true;this.onended?.();}}
class Context{sampleRate=8000;currentTime=0;state='running';nodes=[];destination={};createGain(){return new Node(this);}createDynamicsCompressor(){return new Node(this);}createBufferSource(){return new Node(this);}createBiquadFilter(){return new Node(this);}createStereoPanner(){return new Node(this);}createOscillator(){return new Node(this);}createChannelSplitter(){return new Node(this);}createBuffer(channels,length){const data=Array.from({length:channels},()=>new Float32Array(length));return {getChannelData:i=>data[i]};}}
const wheels=surface=>Array.from({length:4},(_,i)=>({id:i%2?'frontRight':'frontLeft',contact:true,normalLoadN:3700,surface,angularSpeedRadps:60,slipRatio:0}));
test('real mixer distinguishes asphalt/gravel, pause kills transients, dispose disconnects every node',()=>{const context=new Context(),audio=createRaceDrivingAudio({context});audio.update({snapshot:{wheels:wheels('asphalt')},speedMps:20});const asphalt=audio.diagnostics().targets;context.currentTime=.1;audio.update({snapshot:{wheels:wheels('gravel')},speedMps:20});const gravel=audio.diagnostics().targets;assert.ok(gravel.gravel>asphalt.gravel);assert.ok(gravel.rollingLeft<asphalt.rollingLeft);assert.equal(audio.impact({eventId:'one'}),true);assert.equal(audio.impact({eventId:'one'}),false);audio.setActive(false);assert.equal(audio.diagnostics().transientSources,0);assert.equal(audio.diagnostics().rivalLevel,0);audio.dispose();assert.equal(context.nodes.filter(n=>n.connected).length,0);assert.equal(context.nodes.filter(n=>n.started&&!n.stopped).length,0);});
test('regional ambience uses supplied canopy geometry and cancels thunder on pause',()=>{const context=new Context(),audio=createRaceSoundscape({context});audio.update({trackId:'paso_garibaldi',forest:{proximity:.9},windMps:6});const near=audio.diagnostics().targets.birds;context.currentTime=.1;audio.update({trackId:'paso_garibaldi',forest:{proximity:.02},windMps:6});assert.ok(near>audio.diagnostics().targets.birds);audio.thunder();assert.equal(audio.diagnostics().transientSources,1);audio.setActive(false);assert.equal(audio.diagnostics().transientSources,0);assert.ok(Object.values(audio.diagnostics().targets).every(v=>v===0));audio.dispose();assert.equal(context.nodes.filter(n=>n.connected).length,0);});
test('interaction is gesture-context gated, rate limited, and cleans all nodes',()=>{const context=new Context(),audio=createV7InteractionSound({context});context.state='suspended';assert.equal(audio.play(),false);context.state='running';assert.equal(audio.play(),true);assert.equal(audio.play(),false);context.currentTime=.2;assert.equal(audio.play(),true);audio.dispose();assert.equal(context.nodes.filter(n=>n.connected).length,0);});
