import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createCockpitLayoutFile} from '../src/game/cockpit-layout-file.mjs';
import {createCompositionState,createTargetDescriptor,sanitizeCompositionState} from '../src/game/composition-editor-state.mjs';
const rawFactory=JSON.parse(fs.readFileSync(new URL('../assets/configuration/cockpit-layout.json',import.meta.url))),factory=sanitizeCompositionState(rawFactory),copy=x=>structuredClone(x);
const response=data=>({ok:true,json:async()=>copy(data)});const edit=(value,updatedAt='2025-01-01T00:00:00Z')=>({version:3,updatedAt,transforms:{cabin:{position:[value,.167,.648],rotation:[0,0,0],scale:[2.965,2.965,2.965]}},camera:copy(rawFactory.camera)});
function calibrated(layout){assert.ok(layout);for(const id of ['cockpit-complete','front','roof','rearview','dashboard'])assert.deepEqual(layout.transforms[id],factory.transforms[id]);assert.deepEqual(layout.camera,factory.camera);}
test('new local installation uses public calibrated defaults without creating a personal file',async()=>{const calls=[];const file=createCockpitLayoutFile({fetcher:async(url,options)=>{calls.push({url,method:options.method});return response({enabled:true,path:'/isolated/cockpit-layout.json',layout:null});},staticLayoutUrl:null});const value=await file.initialize(null);calibrated(value);assert.equal(file.enabled,true);assert.equal(calls.length,1);assert.equal(calls[0].method,undefined);assert.deepEqual(file.defaults,factory);});
test('new static and local installations resolve the same calibration',async()=>{const local=createCockpitLayoutFile({fetcher:async()=>response({enabled:false}),staticLayoutUrl:null}),pages=createCockpitLayoutFile({fetcher:async()=>response(rawFactory),staticLayoutUrl:'https://example.test/project/assets/configuration/cockpit-layout.json'});assert.deepEqual(await local.initialize(null),await pages.initialize(null));});
test('an older browser edit wins over a newer bundled seed and keeps missing calibrated targets',async()=>{const saved=edit(1.23),before=copy(saved);const file=createCockpitLayoutFile({fetcher:async()=>response(rawFactory),staticLayoutUrl:'/seed.json'});const value=await file.initialize(saved);assert.equal(value.transforms.cabin.position[0],1.23);calibrated(value);assert.deepEqual(saved,before);});
test('a browser edit without a timestamp is still a user edit, not a factory reset',async()=>{const saved=edit(-.4);delete saved.updatedAt;const file=createCockpitLayoutFile({fetcher:async()=>response(rawFactory),staticLayoutUrl:'/seed.json'});assert.equal((await file.initialize(saved)).transforms.cabin.position[0],-.4);});
test('newer disk edits beat older browser edits, while missing targets get defaults',async()=>{const file=createCockpitLayoutFile({fetcher:async()=>response({enabled:true,layout:edit(1.4,'2026-09-12T20:00:00Z')}),staticLayoutUrl:null});const value=await file.initialize(edit(1.1));assert.equal(value.transforms.cabin.position[0],1.4);calibrated(value);});
test('newer browser recovery beats disk without auto-saving over it',async()=>{let puts=0;const file=createCockpitLayoutFile({fetcher:async(_,options)=>{if(options.method==='PUT')puts++;return response({enabled:true,layout:edit(.2)});},staticLayoutUrl:null});const value=await file.initialize(edit(.4,'2026-09-12T20:00:00Z'));assert.equal(value.transforms.cabin.position[0],.4);assert.equal(puts,0);calibrated(value);});
test('disconnected API preserves browser edits and new users still get calibrated defaults',async()=>{const fetcher=async()=>{throw Error('offline')};const a=createCockpitLayoutFile({fetcher,staticLayoutUrl:null}),b=createCockpitLayoutFile({fetcher,staticLayoutUrl:null});const edited=await a.initialize(edit(.9));assert.equal(edited.transforms.cabin.position[0],.9);calibrated(edited);calibrated(await b.initialize(null));assert.equal(a.enabled,false);assert.match(a.error,/offline/);});
test('missing static seed does not erase browser edits or leave a fresh cockpit unassembled',async()=>{const fetcher=async()=>({ok:false,json:async()=>({})});const a=createCockpitLayoutFile({fetcher,staticLayoutUrl:'/missing.json'}),b=createCockpitLayoutFile({fetcher,staticLayoutUrl:'/missing.json'});assert.equal((await a.initialize(edit(.7))).transforms.cabin.position[0],.7);calibrated(await b.initialize(null));});
test('invalid saved input falls back to factory rather than accepting an array as layout',async()=>{const file=createCockpitLayoutFile({fetcher:async()=>response({enabled:true,layout:null}),staticLayoutUrl:null});calibrated(await file.initialize({version:3,transforms:[]}));});
test('explicit reset uses the same factory for every target and camera, then saves that result',()=>{const store=new Map(),state=createCompositionState({initial:edit(.9),defaults:factory,storage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)}});assert.equal(state.resetAll().ok,true);assert.deepEqual(state.getState().transforms,factory.transforms);assert.deepEqual(state.getState().camera,factory.camera);assert.deepEqual(JSON.parse(store.get('cockpit-chevy-layout-editor-v1')).transforms,factory.transforms);});
test('a target reset can restore the reviewed factory rather than the user startup value',()=>{let current=edit(1.2).transforms.cabin;const target=createTargetDescriptor({id:'cabin',defaultState:factory.transforms.cabin,getState:()=>current,applyState:x=>current=x});target.reset();assert.deepEqual(current,factory.transforms.cabin);});
test('explicit save keeps the edited layout and never silently replaces it with defaults',async()=>{const bodies=[];const file=createCockpitLayoutFile({fetcher:async(_,options)=>options.method==='PUT'?(bodies.push(JSON.parse(options.body)),response({ok:true,path:'/saved.json'})):response({enabled:true,layout:null}),staticLayoutUrl:null});await file.initialize(null);assert.equal((await file.save(edit(1.7))).ok,true);assert.equal(bodies[0].transforms.cabin.position[0],1.7);assert.equal(bodies.length,1);});
test('legacy radian layouts preserve rotations when missing targets receive defaults',async()=>{const legacy={version:2,transforms:{cabin:{position:[.4,.1,.6],rotation:[0,Math.PI/2,0],scale:[2,2,2]}}};const file=createCockpitLayoutFile({fetcher:async()=>response({enabled:false}),staticLayoutUrl:null});const value=await file.initialize(legacy);assert.ok(Math.abs(value.transforms.cabin.rotation[1]-90)<1e-8);calibrated(value);});
test('a partial saved transform keeps missing calibrated components',async()=>{const file=createCockpitLayoutFile({fetcher:async()=>response({enabled:false}),staticLayoutUrl:null});const value=await file.initialize({version:3,transforms:{cabin:{position:[.5,.2,.8]}}});assert.deepEqual(value.transforms.cabin.scale,factory.transforms.cabin.scale);assert.deepEqual(value.camera,factory.camera);});
test('real local endpoint: empty directory, explicit edit, reload and later server disconnect',async()=>{
 const {fileURLToPath}=await import('node:url'),path=await import('node:path');const{startServer}=await import('../server.mjs');
 const fixtures=fileURLToPath(new URL('../../Reports/Asfalto_Nacional_v7/cockpit-default-tests/',import.meta.url));fs.mkdirSync(fixtures,{recursive:true});const directory=fs.mkdtempSync(path.join(fixtures,'server-fixture-'));const server=await startServer({root:fileURLToPath(new URL('../',import.meta.url)),port:0,cockpitDataDirectory:directory});
 const fetcher=(url,options={})=>fetch(new URL(url,server.url),{...options,headers:{...options.headers,origin:server.url.replace(/\/$/,'')}});
 try{const file=createCockpitLayoutFile({fetcher,staticLayoutUrl:null});calibrated(await file.initialize(null));assert.deepEqual(fs.readdirSync(directory),[]);const saved=edit(1.33,'2026-09-12T21:00:00Z');assert.equal((await file.save(saved)).ok,true);assert.equal(JSON.parse(fs.readFileSync(path.join(directory,'cockpit-layout.json'))).transforms.cabin.position[0],1.33);const fresh=createCockpitLayoutFile({fetcher,staticLayoutUrl:null});const restored=await fresh.initialize(null);assert.equal(restored.transforms.cabin.position[0],1.33);calibrated(restored);await server.close();const offline=createCockpitLayoutFile({fetcher,staticLayoutUrl:null});assert.equal((await offline.initialize(restored)).transforms.cabin.position[0],1.33);assert.equal(offline.enabled,false);}finally{await server.close();}
});
test('undated browser recovery does not acquire the factory timestamp and outrank a dated disk edit',async()=>{const local=edit(.2);delete local.updatedAt;const file=createCockpitLayoutFile({fetcher:async()=>response({enabled:true,layout:edit(.8,'2025-06-01T00:00:00Z')}),staticLayoutUrl:null});assert.equal((await file.initialize(local)).transforms.cabin.position[0],.8);const pages=createCockpitLayoutFile({fetcher:async()=>response(rawFactory),staticLayoutUrl:'/seed'});assert.equal(Object.hasOwn(await pages.initialize(local),'updatedAt'),false);});
