import test from 'node:test';
import assert from 'node:assert/strict';
import {CHAMPIONSHIPS,AWARDS,createSchedule} from '../src/menu/v7-championship-catalog.mjs?v=250778123f1c9e7f';
import {createRun,beginStage,cancelStage,acceptStage,resumeRun,standings,earnedAwards} from '../src/menu/v7-championship-state.mjs?v=54514a098688545f';
import {resolveEnvironment} from '../src/environment/environment-profiles.mjs?v=315916d6c7fab528';
const entrant={vehicleId:'chevy',class:'Histórica',configurationHash:'fixture-sha256'};
const makeRun=()=>createRun({id:'run1',championshipId:'cinco_horizontes',entrant,createdAt:'2026-09-08T12:00:00.000Z'});
function receipt(run,{player=100,falcon=101,penalty=0}={}){return{resultId:'result-'+run.nextStageIndex,runId:run.id,stageId:run.schedule[run.nextStageIndex].id,attemptId:run.attempt.id,configurationHash:entrant.configurationHash,trackId:run.schedule[run.nextStageIndex].trackId,skyId:run.schedule[run.nextStageIndex].skyId,weather:run.schedule[run.nextStageIndex].weather,source:'authoritative-race',qa:false,valid:true,finishedAt:'2026-09-08T12:01:00.000Z',classification:[{entrantId:'player',status:'finished',checkpointsComplete:true,activeSeconds:player,penaltySeconds:penalty,officialSeconds:player+penalty,finishTick:12000},{entrantId:'falcon',status:'finished',checkpointsComplete:true,activeSeconds:falcon,penaltySeconds:0,officialSeconds:falcon,finishTick:12120}]};}
test('catalog covers 5/10/15 canonical stages, distinct revisits and 20 unique physical awards',()=>{assert.equal(CHAMPIONSHIPS.length,3);for(const [i,c] of CHAMPIONSHIPS.entries()){const s=createSchedule(c.id);assert.equal(s.length,(i+1)*5);const tracks=new Set(s.map(x=>x.trackId));assert.equal(tracks.size,5);for(const id of tracks){const visits=s.filter(x=>x.trackId===id);assert.equal(visits.length,i+1);assert.equal(new Set(visits.map(x=>x.skyId+'/'+x.weather)).size,i+1);}for(const row of s){resolveEnvironment(row.trackId,row.skyId,row.weather);assert.equal(row.laps,1);}}assert.equal(AWARDS.length,20);assert.equal(new Set(AWARDS.map(x=>x.id)).size,20);assert.ok(Math.min(...AWARDS.filter(x=>x.kind==='cup').map(x=>x.heightM))>Math.max(...AWARDS.filter(x=>x.kind==='route-trophy').map(x=>x.heightM)));});
test('cancel/resume preserve stage selection and cannot grant points from stale completion',()=>{const original=makeRun(),run=beginStage(original,'attempt1');assert.equal(original.attempt,null);const r=receipt(run);const canceled=cancelStage(run,'attempt1');assert.equal(canceled.nextStageIndex,0);assert.throws(()=>acceptStage(canceled,r),/attempt/);const resumed=resumeRun(JSON.parse(JSON.stringify(run)));assert.equal(resumed.status,'ready');assert.equal(resumed.attempt,null);assert.deepEqual(earnedAwards(resumed),[]);});
test('invalid, timeout, QA, config mismatch and missing authoritative clock never advance',()=>{const run=beginStage(makeRun(),'a');for(const change of [{valid:false},{source:'timeout'},{qa:true},{configurationHash:'different'},{weather:'storm'}])assert.throws(()=>acceptStage(run,{...receipt(run),...change}));const missing=receipt(run);delete missing.classification[0].officialSeconds;assert.throws(()=>acceptStage(run,missing));const checkpoints=receipt(run);checkpoints.classification[0].checkpointsComplete=false;assert.throws(()=>acceptStage(run,checkpoints));assert.equal(run.accepted.length,0);});
test('penalized official time determines points, duplicate receipt is idempotent',()=>{const run=beginStage(makeRun(),'a'),r=receipt(run,{penalty:2});const accepted=acceptStage(run,r);assert.equal(accepted.nextStageIndex,1);assert.deepEqual(standings(accepted).map(x=>[x.entrantId,x.points]),[['falcon',3],['player',1]]);assert.equal(acceptStage(accepted,r),accepted);assert.throws(()=>acceptStage(accepted,{...r,resultId:'different'}));assert.equal(earnedAwards(accepted).length,0);});
test('five valid victories grant five route trophies and one cup only at completion',()=>{let run=makeRun();for(let i=0;i<5;i++){run=beginStage(run,'a'+i);run=acceptStage(run,receipt(run));assert.equal(earnedAwards(run).filter(x=>x.kind==='cup').length,i===4?1:0);}assert.equal(run.status,'completed');assert.equal(earnedAwards(run).filter(x=>x.kind==='route-trophy').length,5);assert.throws(()=>beginStage(run,'extra'));assert.equal(resumeRun(run).status,'completed');});
test('exact ties split stage points and final complete tie is explicitly shared',()=>{let run=makeRun();for(let i=0;i<5;i++){run=beginStage(run,'a'+i);run=acceptStage(run,receipt(run,{falcon:100}));}assert.deepEqual(standings(run).map(x=>x.points),[10,10]);assert.equal(earnedAwards(run).find(x=>x.kind==='cup').shared,true);});
test('later championships require actual completed predecessor and retain snapshot across save',()=>{assert.throws(()=>createRun({id:'r2',championshipId:'oficio_ruta',entrant,createdAt:'2026-09-08T12:00:00Z'}),/locked/);const run=createRun({id:'r2',championshipId:'oficio_ruta',entrant,createdAt:'2026-09-08T12:00:00Z',completedChampionshipIds:['cinco_horizontes']});assert.equal(resumeRun(JSON.parse(JSON.stringify(run))).schedule.length,10);});
test('restoring persisted results recomputes points and rejects edited stage cursor or missing arrival',()=>{let run=beginStage(makeRun(),'a');run=acceptStage(run,receipt(run));const altered=JSON.parse(JSON.stringify(run));altered.accepted[0].classification[0].points=999;assert.equal(standings(resumeRun(altered)).find(x=>x.entrantId==='player').points,3);assert.throws(()=>resumeRun({...altered,nextStageIndex:5}));altered.accepted[0].classification[0].status='dnf';assert.throws(()=>resumeRun(altered));});
