import test from 'node:test';
import assert from 'node:assert/strict';
import { createExperienceFlow, inputIsEditing, activityHud, resultSummary } from '../src/menu/v7-experience-state.mjs';
import { engineMix, mechanicalEvents, regionalAcoustics } from '../src/audio/v7-audio-state.mjs';
test('superseded loading cannot commit and resources release once',()=>{
 const flow=createExperienceFlow();let released=0;const first=flow.begin('loading');first.own(()=>released++);flow.begin('workshop');assert.equal(first.commit('driving'),false);assert.equal(released,1);assert.equal(flow.state.phase,'workshop');flow.dispose();assert.equal(released,1);
});
test('all modal phases gate race input and sound',()=>{
 const flow=createExperienceFlow();for(const phase of ['workshop','loading','opening','paused','editor','results']){flow.begin(phase);assert.equal(flow.state.drivingInput,false);assert.equal(flow.state.raceAudio,false);}flow.begin('driving');assert.equal(flow.state.drivingInput,true);flow.setHidden(true);assert.equal(flow.state.raceAudio,false);flow.setHidden(false);assert.equal(flow.state.drivingInput,true);
});
test('editing focus never becomes a driving command',()=>{for(const tagName of ['INPUT','TEXTAREA','SELECT','BUTTON'])assert.equal(inputIsEditing({tagName}),true);assert.equal(inputIsEditing({isContentEditable:true}),true);assert.equal(inputIsEditing({tagName:'CANVAS'}),false);});
test('lean HUD preserves alerts and opt out',()=>{assert.equal(activityHud({enabled:false,activity:'free'}).compact,false);const hud=activityHud({enabled:true,activity:'free',speedMps:10,gear:3,alerts:['Presión de aceite']});assert.equal(hud.speedKph,36);assert.equal(hud.compact,true);assert.deepEqual(hud.alerts,['Presión de aceite']);assert.equal(activityHud({enabled:true,activity:'race'}).showTiming,true);});
test('results distinguish active time, penalties and unknown validity',()=>{const r=resultSummary({activeSeconds:60,penaltySeconds:4,valid:false,reason:'Atajo'});assert.equal(r.totalSeconds,64);assert.equal(r.validity,'No válida');assert.equal(resultSummary({}).totalSeconds,null);assert.equal(resultSummary({}).validity,'Sin validar');});
test('six cylinder separates admission and overrun at actual RPM',()=>{const load=engineMix({rpm:2400,load:.8,throttle:.8,cameraMode:'chase'}),coast=engineMix({rpm:2400,load:-.6,throttle:0,cameraMode:'chase'});assert.equal(load.firingHz,120);assert.ok(load.intakeLevel>coast.intakeLevel);assert.ok(coast.retention>load.retention);assert.ok(engineMix({rpm:2400,load:.8,throttle:.8,cameraMode:'cockpit'}).exhaustLevel<load.exhaustLevel);assert.equal(engineMix({rpm:0}).engineLevel,0);});
test('mechanical cues follow transitions once without initial stall',()=>{assert.deepEqual(mechanicalEvents(null,{rpm:0,gear:0}),[]);assert.deepEqual(mechanicalEvents({rpm:900,gear:1},{rpm:100,gear:1,running:false}),['stall']);assert.deepEqual(mechanicalEvents({rpm:1400,gear:1},{rpm:1100,gear:2}),['shift']);assert.deepEqual(mechanicalEvents({rpm:1100,gear:2},{rpm:1100,gear:2}),[]);});
test('regional emitter proximity changes forest acoustics',()=>{const forest=regionalAcoustics({trackId:'paso_garibaldi',forest:{proximity:.9}}),clearing=regionalAcoustics({trackId:'paso_garibaldi',forest:{proximity:.05}});assert.ok(forest.birds>clearing.birds);assert.equal(forest.insects,0);assert.equal(regionalAcoustics({trackId:'aconcagua_horcones',forest:{proximity:1}}).birds,0);assert.ok(regionalAcoustics({trackId:'cataratas_iguazu',forest:{proximity:1},night:true}).insects>0);});
