import test from 'node:test';
import assert from 'node:assert/strict';
import {createPhysicalRoadTestValidator} from '../src/game/physical-road-tests.mjs?v=9ff50f2b5edd041b';
import {getEarnedDisplayItems} from '../src/menu/v7-earned-collection.mjs?v=d14e43cdb1271985';
const sessionModule=await import('../src/menu/v7-roadtest-session.mjs?v=4450177759448c35').catch(()=>({}));
const profileModule=await import('../src/menu/v7-roadtest-profile.mjs?v=9d8202ef5e8ea7fd').catch(()=>({}));
const receiptModule=await import('../src/menu/v7-roadtest-receipts.mjs?v=b2a818b5bf186307').catch(()=>({}));
const identity={testId:'vmax',sessionId:'session-1',configurationHash:'a'.repeat(64),trackId:'dos_lagos',vehicleId:'chevy',class:'Histórica',sessionSequence:7};
function frame(tick,{speed=50,running=true,...extra}={}){return{tick,sessionSequence:7,running,snapshot:{fixedHz:120,chassis:{position:[speed*tick/120,0,0],rotation:[0,0,0,1],linearVelocity:[speed,0,0],acceleration:[0,0,0]},wheels:Array.from({length:4},()=>({contact:true})),controls:{throttle:1,brake:0,steer:0},gearbox:{gear:4},clutch:{engagement:1},brakes:{wheelBrakeTorquesNm:[0,0,0,0]},engine:{rpm:2600,torqueNm:80}},projection:{raceProgress:speed*tick/120,lateral:0,speedAlongRouteMps:speed,routeHalfWidthM:5,valid:true,continuous:true},environment:{wetness:0,gripMultiplier:1},qa:false,teleports:0,recoveries:0,referenceChart:0,...extra};}
function receipt(){const validator=createPhysicalRoadTestValidator(identity);for(let tick=1;tick<=361;tick++)validator.sample({...frame(tick),...identity});return{...validator.getReceipt({resultId:'result-1',finishedAt:'2026-09-09T12:00:00.000Z'}),sessionSequence:7};}
function world(){let observer=null;return{getPhysicalObservationState:()=>({sessionSequence:7,qa:false,referenceChart:0}),subscribePhysicalSteps(value){observer=value;return()=>{observer=null;};},emit(value){observer?.sample(value);},invalidate(reason){observer?.invalidated(reason);},rebase(event={referenceChart:1}){observer?.rebase(event);},count:()=>Number(!!observer),clearRoadTestGates(){}};}
function diskStore(initial={storageRevision:0}){let current=structuredClone(initial),disk=JSON.stringify(initial),writes=0,mode='normal';const storage={getItemPersistent:()=>disk,setItemPersistent(key,text){writes++;if(mode==='drop')return;if(mode==='corrupt'){disk='{}';return;}disk=text;if(mode==='uncertain')throw Error('write completed but acknowledgement lost');}};return{storage,getProfile:()=>current,replaceProfile:p=>current=p,withLock:fn=>fn(),setMode:v=>mode=v,writeDisk:p=>disk=JSON.stringify(p),disk:()=>JSON.parse(disk),writes:()=>writes};}
test('physical host consumes all substeps and completes once without RAF scoring',()=>{assert.equal(typeof sessionModule.createRoadTestSession,'function');const w=world(),completed=[];const session=sessionModule.createRoadTestSession({...identity,world:w,onCompleted:r=>completed.push(r),now:()=> '2026-09-09T12:00:00.000Z',newId:()=> 'result-1'});for(let tick=1;tick<=400;tick++)w.emit(frame(tick));assert.equal(completed.length,1);assert.equal(completed[0].measurement.value,180);assert.equal(completed[0].evidence.sampleCount,361);assert.equal(completed[0].sessionSequence,7);assert.equal(session.getState().phase,'completed');assert.equal(w.count(),0);});
test('paused ticks never create active time and resume stays contiguous',()=>{assert.equal(typeof sessionModule.createRoadTestSession,'function');const w=world(),session=sessionModule.createRoadTestSession({...identity,world:w});for(let tick=1;tick<=10;tick++)w.emit(frame(tick,{running:false}));assert.equal(session.getState().sampleCount,0);w.emit(frame(11));assert.equal(session.getState().sampleCount,1);});
test('gaps, QA, recovery, lifecycle and rebase invalidate and detach without publication',()=>{assert.equal(typeof sessionModule.createRoadTestSession,'function');for(const fault of ['gap','qa','recovery','sequence','cancel','rebase','host-invalidated']){const w=world(),completed=[],session=sessionModule.createRoadTestSession({...identity,world:w,onCompleted:r=>completed.push(r)});w.emit(frame(1));if(fault==='cancel')session.cancel();else if(fault==='rebase')w.rebase();else if(fault==='host-invalidated')w.invalidate('restart');else w.emit(frame(fault==='gap'?3:2,fault==='qa'?{qa:true}:fault==='recovery'?{recoveries:1}:fault==='sequence'?{sessionSequence:8}:{}));assert.equal(session.getState().phase,'invalid',fault);assert.equal(w.count(),0,fault);assert.equal(completed.length,0,fault);}});
test('displayed speedometer sample maps physicalTick to instrument sampleTick',()=>{assert.equal(typeof sessionModule.createRoadTestSession,'function');const w=world(),completed=[],session=sessionModule.createRoadTestSession({...identity,testId:'speedo',world:w,getInstrument:()=>({indicatedKph:101,physicalTick:tickNow}),onCompleted:r=>completed.push(r)});let tickNow=0;for(let tick=1;tick<=600;tick++){tickNow=tick;w.emit(frame(tick,{speed:100/3.6}));}assert.equal(session.getState().valid,true);assert.ok(Math.abs(completed[0].measurement.value-1)<1e-9);});
test('receipt reader rejects old valid sheets and malformed physical thresholds',()=>{assert.equal(typeof receiptModule.validateRoadTestReceipt,'function');const r=receipt();assert.equal(receiptModule.validateRoadTestReceipt(r).testId,'vmax');for(const changed of [{qa:true},{sessionSequence:null},{configurationHash:''},{evidence:{...r.evidence,sampleCount:0}},{measurement:{...r.measurement,value:0}},{measurement:{...r.measurement,stableSeconds:2}},{source:'legacy-sheet'}])assert.throws(()=>receiptModule.validateRoadTestReceipt({...r,...changed}));assert.throws(()=>receiptModule.validateRoadTestReceipt({testId:'vmax',valid:true,main:200}));});
test('receipt persistence requires exact readback and never publishes on dropped/corrupt writes',async()=>{assert.equal(typeof profileModule.createRoadTestProfileStore,'function');for(const mode of ['drop','corrupt']){const fixture=diskStore(),store=profileModule.createRoadTestProfileStore(fixture);fixture.setMode(mode);await assert.rejects(store.accept(receipt()));assert.equal(fixture.getProfile().roadTestsV7,undefined);assert.equal(store.diagnostics().pending,true);}});
test('persistent receipt is idempotent, frozen and earns only its catalog medal',async()=>{assert.equal(typeof profileModule.createRoadTestProfileStore,'function');const fixture=diskStore({storageRevision:0,sheets:[{testId:'slalom',valid:true}],xp:900}),store=profileModule.createRoadTestProfileStore(fixture);await store.accept(receipt());await store.accept(receipt());assert.equal(fixture.writes(),1);assert.equal(fixture.getProfile().storageRevision,1);assert.ok(Object.isFrozen(fixture.getProfile().roadTestsV7.receipts['result-1']));assert.deepEqual(getEarnedDisplayItems(fixture.getProfile()).map(x=>x.id),['test:vmax']);assert.equal(getEarnedDisplayItems(fixture.disk())[0].receiptId,'result-1');});
test('unknown successful write retries same receipt once; changed duplicate and revision conflicts fail',async()=>{assert.equal(typeof profileModule.createRoadTestProfileStore,'function');const fixture=diskStore(),store=profileModule.createRoadTestProfileStore(fixture);fixture.setMode('uncertain');await assert.rejects(store.accept(receipt()));assert.equal(fixture.getProfile().roadTestsV7,undefined);fixture.setMode('normal');const result=await store.retryPending();assert.equal(result.recovered,true);assert.equal(fixture.writes(),1);await assert.rejects(store.accept({...receipt(),measurement:{...receipt().measurement,value:181}}));fixture.writeDisk({...fixture.disk(),storageRevision:99});await assert.rejects(store.accept({...receipt(),resultId:'result-2',sessionId:'session-2'}));});
test('waiting disk lock cannot commit a canceled session',async()=>{assert.equal(typeof profileModule.createRoadTestProfileStore,'function');const fixture=diskStore();let release,current=true;fixture.withLock=fn=>new Promise((resolve,reject)=>release=()=>{try{resolve(fn());}catch(error){reject(error);}});const store=profileModule.createRoadTestProfileStore(fixture),pending=store.accept(receipt(),{isCurrent:()=>current});await new Promise(setImmediate);current=false;release();await assert.rejects(pending);assert.equal(fixture.writes(),0);});

test('legitimate rigid rebase preserves physical progress and observer identity',()=>{assert.equal(typeof sessionModule.createRoadTestSession,'function');const w=world(),session=sessionModule.createRoadTestSession({...identity,world:w});w.emit(frame(1));w.rebase({referenceChart:1,matrix:[1,0,0,0,0,1,0,0,0,0,1,0,100,0,0,1]});const next=frame(2,{referenceChart:1});next.snapshot.chassis.position[0]+=100;w.emit(next);assert.equal(session.getState().phase,'running');assert.equal(session.getState().sampleCount,2);assert.equal(w.count(),1);});

// Mathematical sample fixtures exercise the receipt boundary; these are not driven game attempts.
function physicalReceipt(testId){
 const gates=Array.from({length:8},(_,i)=>({id:'slalom-'+(i+1),center:[10+i*16,0,i%2?.9:-.9],forward:[1,0,0],left:[0,0,1],halfWidthM:1.5}));
 const metadata={...identity,testId,sessionId:'session-'+testId},validator=createPhysicalRoadTestValidator({...metadata,definition:{gates,displacementLiters:4.097}});let tick=0,x=0;
 function push({speed=0,position,gear=4,steer=0,brake=0,wetness=0,grip=1,acceleration=[0,0,0],rotation=[0,0,0,1]}={}){tick++;x+=speed/120;const f=frame(tick,{speed,sessionId:metadata.sessionId,configurationHash:metadata.configurationHash,environment:{wetness,gripMultiplier:grip},instrument:{indicatedKph:101,sampleTick:tick}});f.snapshot.chassis.position=position||[x,0,0];f.snapshot.chassis.rotation=rotation;f.snapshot.chassis.acceleration=acceleration;f.snapshot.controls={steer,brake,throttle:.8};f.snapshot.gearbox.gear=gear;f.snapshot.brakes.wheelBrakeTorquesNm=[brake*500,brake*500,brake*500,brake*500];f.projection.raceProgress=x;validator.sample(f);}
 if(['accel100','accel160','m500','m1000'].includes(testId)){for(let i=0;i<61;i++)push();for(let i=0;i<4000&&!validator.getState().objectiveComplete;i++)push({speed:Math.min(50,i*.1)});}
 if(testId==='vmax')for(let i=0;i<361;i++)push({speed:50});
 if(testId==='recovery'){push({speed:21});push({speed:23});push({speed:34});}
 if(testId==='brake100'){push({speed:27});push({speed:28});push({speed:28,brake:1});for(let i=0;i<300;i++)push({speed:Math.max(0,28-i*.12),brake:1});}
 if(testId==='slalom')for(let i=0;i<4000&&!validator.getState().objectiveComplete;i++){const p=(i+1)*4/120;push({speed:4,position:[p,0,-.9*Math.cos((p-10)*Math.PI/16)]});}
 if(testId==='turn')for(let i=0;i<2400&&!validator.getState().objectiveComplete;i++){const a=i*2/120/6,h=a+Math.PI/2;push({speed:2,position:[6*Math.cos(a),0,6*Math.sin(a)],rotation:[0,-Math.sin(h/2),0,Math.cos(h/2)],steer:.48});}
 if(testId==='wet')for(let i=0;i<15000&&!validator.getState().objectiveComplete;i++)push({speed:i<100?20:i<200?20-(i-100)*.04:16,wetness:1,grip:.66,brake:i>=100&&i<200?1:0,acceleration:[0,0,.6]});
 if(testId==='speedo')for(let i=0;i<600;i++)push({speed:100/3.6});
 if(testId==='consumption')for(let i=0;i<18000&&!validator.getState().objectiveComplete;i++)push({speed:60/3.6});
 assert.equal(validator.getState().objectiveComplete,true,testId+': '+JSON.stringify(validator.getState()));
 return{...validator.getReceipt({resultId:'result-'+testId,finishedAt:'2026-09-09T12:00:00.000Z'}),sessionSequence:7};
}
test('all twelve validator receipts replay to twelve distinct catalog medals and corrupt evidence cannot add one',()=>{
 const ids=['vmax','accel100','accel160','m500','m1000','recovery','brake100','slalom','turn','wet','speedo','consumption'],receipts={};
 for(const id of ids){const r=physicalReceipt(id);assert.equal(receiptModule.validateRoadTestReceipt(r).testId,id);receipts[r.resultId]=r;}
 const profile={roadTestsV7:{schema:'asfalto-road-tests/v1',revision:12,receipts}},items=getEarnedDisplayItems(JSON.parse(JSON.stringify(profile)));
 assert.deepEqual(items.map(x=>x.id),ids.map(id=>'test:'+id));assert.equal(new Set(items.map(x=>x.shape)).size,12);
 const corrupted=structuredClone(profile);corrupted.roadTestsV7.receipts['result-slalom'].evidence.gates[4].tick=0;assert.equal(getEarnedDisplayItems(corrupted).length,11);
});
test('two tabs sharing one lock cannot overwrite another accepted physical receipt',async()=>{
 let disk='{}',a={},b={},queue=Promise.resolve();const storage={getItemPersistent:()=>disk,setItemPersistent(_key,value){disk=value;}},withLock=fn=>{const result=queue.then(fn);queue=result.catch(()=>{});return result;};
 const first=profileModule.createRoadTestProfileStore({storage,withLock,getProfile:()=>a,replaceProfile:p=>a=p}),second=profileModule.createRoadTestProfileStore({storage,withLock,getProfile:()=>b,replaceProfile:p=>b=p});
 const results=await Promise.allSettled([first.accept(physicalReceipt('vmax')),second.accept(physicalReceipt('speedo'))]);assert.equal(results[0].status,'fulfilled');assert.equal(results[1].status,'rejected');assert.deepEqual(Object.keys(JSON.parse(disk).roadTestsV7.receipts),['result-vmax']);
});

test('canceling a queued failed save clears retry state even when the lock completes later',async()=>{const fixture=diskStore();let release,current=true;fixture.withLock=fn=>new Promise((resolve,reject)=>release=()=>{try{resolve(fn());}catch(error){reject(error);}});const store=profileModule.createRoadTestProfileStore(fixture),pending=store.accept(receipt(),{isCurrent:()=>current});await new Promise(setImmediate);current=false;store.clearPending();release();await assert.rejects(pending);assert.equal(store.diagnostics().pending,false);});

test('only a persisted physical receipt grants progression and duplicate retries grant none',async()=>{const fixture=diskStore({storageRevision:0,xp:0,level:1,workshopTokens:2,axes:{dominio:0,ruta:0},unlocked:[]}),store=profileModule.createRoadTestProfileStore(fixture);fixture.setMode('drop');await assert.rejects(store.accept(receipt()));assert.equal(fixture.getProfile().xp,0);assert.equal(fixture.getProfile().workshopTokens,2);fixture.setMode('normal');await store.retryPending();await store.accept(receipt());assert.equal(fixture.getProfile().xp,14);assert.equal(fixture.getProfile().axes.dominio,7);assert.equal(fixture.getProfile().axes.ruta,7);assert.equal(fixture.getProfile().workshopTokens,4);for(let i=2;i<=6;i++)await store.accept({...receipt(),sessionId:'session-'+i,resultId:'result-'+i});assert.equal(fixture.getProfile().level,2);assert.equal(fixture.getProfile().workshopTokens,15);assert.ok(fixture.getProfile().unlocked.includes('sierraMap'));});

for(const vehicleId of ['chevy','chevy_400_1957','chevrolet_1969'])test('selectable '+vehicleId+' completes, persists and retains its presentation identity',async()=>{
 const w=world(),completed=[],session=sessionModule.createRoadTestSession({...identity,vehicleId,world:w,onCompleted:r=>completed.push(r),now:()=> '2026-09-09T12:00:00.000Z',newId:()=> 'result-'+vehicleId});
 assert.doesNotThrow(()=>{for(let tick=1;tick<=361;tick++)w.emit(frame(tick));});assert.equal(session.getState().phase,'completed');assert.equal(completed.length,1);assert.equal(completed[0].vehicleId,vehicleId);
 const fixture=diskStore(),store=profileModule.createRoadTestProfileStore(fixture);await store.accept(completed[0]);const items=getEarnedDisplayItems(fixture.disk());assert.equal(items.length,1);assert.equal(items[0].vehicleId,vehicleId);assert.equal(items[0].receiptId,'result-'+vehicleId);
});
for(const vehicleId of ['unknown-vehicle','falcon','toString'])test('receipt rejects nonselectable vehicle '+vehicleId,()=>{assert.throws(()=>receiptModule.validateRoadTestReceipt({...receipt(),vehicleId}),/vehículo/);});
for(const failure of ['clock-throws','invalid-date','empty-result-id','receipt-validation'])test('receipt '+failure+' ends observably invalid with no escaped exception or publication',()=>{
 const w=world(),completed=[],invalid=[],options={...identity,world:w,onCompleted:r=>completed.push(r),onInvalidated:s=>invalid.push(s),now:()=> '2026-09-09T12:00:00.000Z',newId:()=> 'result-failure'};
 if(failure==='clock-throws')options.now=()=>{throw Error('clock unavailable');};if(failure==='invalid-date')options.now=()=> 'not a date';if(failure==='empty-result-id')options.newId=()=> '';if(failure==='receipt-validation')options.vehicleId='unknown-vehicle';
 const session=sessionModule.createRoadTestSession(options);assert.doesNotThrow(()=>{for(let tick=1;tick<=400;tick++)w.emit(frame(tick));});
 assert.equal(completed.length,0);assert.equal(invalid.length,1);assert.equal(invalid[0].phase,'invalid');assert.equal(invalid[0].valid,false);assert.equal(invalid[0].objectiveComplete,false);assert.equal(invalid[0].measurement,null);assert.ok(invalid[0].invalidReasons.includes('receipt-creation-or-validation-failed'));assert.deepEqual(session.getState(),invalid[0]);assert.equal(session.getReceipt(),null);assert.equal(w.count(),0);session.cancel();assert.equal(invalid.length,1);
});
