import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
const source=readFileSync(new URL('../src/render/vehicle-presentation.mjs?v=6698fa8c93c2dcfc',import.meta.url),'utf8');
const block=source.slice(source.indexOf('  for(const m of materials) {'),source.indexOf('  replacedMaterials.forEach'));
const apply=new Function('materials','vehicle','uniforms','T','definition','brakes','headlamps',block);
const payload=JSON.parse(readFileSync(new URL('../assets/manifests/workshop-bootstrap.json?v=71e24e64d3ef5ec5',import.meta.url),'utf8'));
const T=await import('data:text/javascript;base64,'+gunzipSync(Buffer.from(payload.threeCoreGz,'base64')).toString('base64'));
function material(vehicle,name,hook,key){const m=new T.MeshStandardMaterial();m.name=name;m.userData.vehicleAuthoredMatrix=new T.Matrix4();if(hook)m.onBeforeCompile=hook;if(key)m.customProgramCacheKey=key;const uniforms={vehiclePaint:{value:new T.Color()},vehicleDirt:{value:0},vehicleWet:{value:0},vehicleDust:{value:new T.Color()}};apply(new Set([m]),vehicle,uniforms,T,{},[],[]);const shader={uniforms:{},vertexShader:'#include <begin_vertex>',fragmentShader:'#include <map_fragment>\n#include <roughnessmap_fragment>'};m.onBeforeCompile(shader);return{m,shader,key:m.customProgramCacheKey(),glsl:shader.vertexShader+'\n'+shader.fragmentShader,uniforms}}
test('surface keys exactly group the four generated GLSL variants across vehicle and atlas names',()=>{const rows=[];for(const vehicle of ['chevy','falcon','chevy_400_1957'])for(const name of ['Paint','PaintAtlas','StripeAtlas'])rows.push(material(vehicle,name));for(const a of rows)for(const b of rows)assert.equal(a.key===b.key,a.glsl===b.glsl,`${a.m.name}/${b.m.name}`);assert.equal(new Set(rows.map(r=>r.key)).size,4)});
test('shared shaders retain independent uniforms and authoring matrices',()=>{const a=material('falcon','Paint'),b=material('chevy_400_1957','PaintAtlas');assert.equal(a.key,b.key);assert.notEqual(a.shader.uniforms.vehiclePaint,b.shader.uniforms.vehiclePaint);assert.notEqual(a.shader.uniforms.vehicleAuthoringMatrix.value,b.shader.uniforms.vehicleAuthoringMatrix.value);a.uniforms.vehiclePaint.value.set('#ff0000');assert.notEqual(a.uniforms.vehiclePaint.value.getHex(),b.uniforms.vehiclePaint.value.getHex())});
test('prior hooks and their declared shader identities remain isolated',()=>{const hookA=shader=>{shader.vertexShader+='\n// prior A'},hookB=shader=>{shader.vertexShader+='\n// prior B'};const a=material('falcon','Paint',hookA,()=> 'prior-a'),b=material('falcon','Paint',hookB,()=> 'prior-b');assert.notEqual(a.glsl,b.glsl);assert.notEqual(a.key,b.key);assert.match(a.shader.vertexShader,/prior A/);const c=material('falcon','Paint',hookA),d=material('falcon','Paint',hookB);assert.notEqual(c.key,d.key)});
