import test from 'node:test';import assert from 'node:assert/strict';import {THREE as T} from './cinematic-three.mjs';
let createVehicleContactOcclusion;try{({createVehicleContactOcclusion}=await import('../src/render/vehicle-contact-occlusion.mjs?v=c70113c41f7973bf'));}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}
const ids=['frontLeft','frontRight','rearLeft','rearRight'];const snapshot=(dx=0)=>({chassis:{position:[dx,.56,0],rotation:[0,0,0,1]},wheels:ids.map((id,i)=>({id,contact:true,point:[dx+(i<2?1.4:-1.4),0,i%2?.72:-.72],normal:[0,1,0],surface:'asphalt'}))});
function fixture(){assert.equal(typeof createVehicleContactOcclusion,'function','contact implementation missing');const scene=new T.Scene(),canvas=new EventTarget();const effect=createVehicleContactOcclusion(T,{scene,renderer:{domElement:canvas}});return{scene,canvas,effect};}
test('actual contacts produce five bounded soft patches in one mesh, no target or texture',()=>{const f=fixture(),s=snapshot();const frozen=JSON.stringify(s);f.effect.update(s,s,1);assert.equal(f.effect.diagnostics().patches,5);assert.equal(f.effect.mesh.geometry.drawRange.count,30);assert.equal(f.effect.diagnostics().steadyDrawCalls,1);assert.equal(f.effect.mesh.material.forceSinglePass,true);assert.equal(JSON.stringify(s),frozen);const p=f.effect.mesh.geometry.attributes.position.array;assert.ok([...p].every(Number.isFinite));assert.ok([...p].filter((_,i)=>i%3===1).every(y=>Math.abs(y-.009)<1e-6));f.effect.dispose();});
test('no contact, invalid points and invalid normals never leave a floating shadow',()=>{const f=fixture(),s=snapshot();for(const wheel of s.wheels)wheel.contact=false;f.effect.update(s,s,1);assert.equal(f.effect.mesh.visible,false);s.wheels[0].contact=true;s.wheels[0].point[1]=NaN;f.effect.update(s,s,1);assert.equal(f.effect.mesh.visible,false);s.wheels[0].point=[0,0,0];s.wheels[0].normal=[0,0,0];f.effect.update(s,s,1);assert.equal(f.effect.mesh.visible,false);f.effect.dispose();});
test('interpolates only persistent contacts, current contact loss takes effect immediately',()=>{const f=fixture(),a=snapshot(),b=snapshot(2);f.effect.update(a,b,.5);let p=f.effect.mesh.geometry.attributes.position.array;assert.ok(Math.abs((p[0]+p[3])/2-2.4)<1e-6);b.wheels[0].contact=false;f.effect.update(a,b,.5);assert.equal(f.effect.diagnostics().patches,3);b.wheels.forEach(w=>w.contact=false);f.effect.update(a,b,.5);assert.equal(f.effect.mesh.visible,false);f.effect.dispose();});
test('sloped contacts remain on their plane; mixed or noncoplanar contacts omit underbody',()=>{const f=fixture(),s=snapshot(),n=[0,1,-.2],length=Math.hypot(...n);for(const w of s.wheels){w.normal=n.map(v=>v/length);w.point[1]=.2*w.point[2];}f.effect.update(s,s,1);assert.equal(f.effect.diagnostics().patches,5);const p=f.effect.mesh.geometry.attributes.position.array;for(let i=0;i<18;i+=3)assert.ok(Math.abs(p[i+1]-.2*p[i+2]-.009*length)<1e-6);s.wheels[0].surface='grass';f.effect.update(s,s,1);assert.equal(f.effect.diagnostics().patches,4);s.wheels[0].surface='asphalt';s.wheels[0].point[1]+=1;f.effect.update(s,s,1);assert.equal(f.effect.diagnostics().patches,4);f.effect.dispose();});
test('twenty updates reuse buffers, context loss frees handles, dispose removes owner and cannot revive',()=>{const f=fixture(),s=snapshot(),buffer=f.effect.mesh.geometry.attributes.position.array;let freed=0;f.effect.mesh.geometry.addEventListener('dispose',()=>freed++);for(let i=0;i<20;i++)f.effect.update(s,s,1);assert.equal(f.effect.mesh.geometry.attributes.position.array,buffer);f.canvas.dispatchEvent(new Event('webglcontextlost'));assert.equal(freed,1);assert.equal(f.effect.mesh.visible,false);f.effect.update(s,s,1);assert.equal(f.effect.mesh.visible,true);f.effect.dispose();f.effect.dispose();assert.equal(f.scene.children.length,0);assert.equal(f.effect.update(s,s,1),false);f.canvas.dispatchEvent(new Event('webglcontextlost'));assert.equal(freed,2);});

import {compileVisiblePass} from '../src/render/pass-preparation.mjs?v=258173b4dba723d7';
test('hidden support is prepared without making it visible or drawing it',async()=>{const f=fixture(),nodes=[],camera=new T.Camera(),renderer={compileAsync(view){view.traverse(node=>nodes.push(node));return Promise.resolve();}};await compileVisiblePass(renderer,f.scene,camera);assert.ok(nodes.includes(f.effect.mesh));assert.equal(f.effect.mesh.visible,false);assert.equal(f.effect.mesh.geometry.drawRange.count,0);f.effect.dispose();});
