import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {createVehicleLighting} from '../src/render/vehicle-lighting.mjs?v=cbf59234f390cc3e';
const payload=JSON.parse(readFileSync(new URL('../assets/manifests/workshop-bootstrap.json',import.meta.url),'utf8'));
const T=await import('data:text/javascript;base64,'+gunzipSync(Buffer.from(payload.threeCoreGz,'base64')).toString('base64'));
function setup(){const root=new T.Group(),scene=new T.Scene();scene.add(root);return{scene,api:createVehicleLighting(T,{vehicle:'chevy',root,scene})}}
const settle=(api)=>{for(let i=0;i<40;i++)api.update({dt:.1,quality:'balanced'})};
const structure=api=>api.getLights().map(l=>({visible:l.visible,castShadow:l.castShadow,mapped:!!l.map}));
test('off low high retain projector and shadow shader counts while preserving filament fade',()=>{const{api}=setup();const expected=structure(api);assert.ok(expected.every(l=>l.visible));assert.equal(expected.filter(l=>l.castShadow).length,1);assert.equal(api.diagnostics().visibleBeams,0);for(const mode of ['low','high','off']){api.setMode(mode);if(mode==='off')assert.ok(api.getLights()[0].intensity>0,'off retains filament fade');settle(api);assert.deepEqual(structure(api),expected);assert.equal(api.diagnostics().visibleBeams,mode==='off'?0:2)}api.dispose()});
test('dark headlights retain shadow map but skip shadow rendering and resume on ignition',()=>{const{api}=setup(),light=api.getLights()[0];assert.equal(light.shadow.autoUpdate,false);assert.equal(light.shadow.needsUpdate,false);api.setMode('low');api.update({dt:.1});assert.equal(light.shadow.autoUpdate,true);assert.equal(light.shadow.needsUpdate,true);light.shadow.needsUpdate=false;const map={dispose(){}};light.shadow.map=map;api.setMode('off');settle(api);assert.equal(light.shadow.autoUpdate,false);assert.equal(light.shadow.needsUpdate,false);assert.equal(light.shadow.map,map);api.setMode('high');api.update({dt:.1});assert.equal(light.shadow.autoUpdate,true);assert.equal(light.shadow.needsUpdate,true);api.dispose()});
test('inactive calibration eco and dispose keep their intended shadow and lifecycle controls',()=>{const{api,scene}=setup();api.setMode('low');settle(api);api.setActive(false);assert.ok(api.getLights().every(l=>!l.visible&&!l.castShadow&&!l.shadow.autoUpdate&&l.intensity===0));assert.equal(api.diagnostics().visibleBeams,0);api.setActive(true);assert.equal(api.getLights()[0].shadow.autoUpdate,true);api.update({quality:'eco'});assert.ok(api.getLights().every(l=>!l.castShadow&&!l.shadow.autoUpdate));api.setCalibration({castShadow:true});api.update({quality:'balanced'});assert.ok(api.getLights().every(l=>l.castShadow));api.setCalibration({enabled:false});assert.equal(api.diagnostics().visibleBeams,0);assert.ok(api.getLights().every(l=>!l.shadow.autoUpdate));api.dispose();assert.equal(scene.children.length,1);assert.equal(api.update(),false);assert.equal(api.dispose(),false)});

test("disposing a lit rig removes lights and reports no visible beams",()=>{const{api}=setup();api.setMode("low");settle(api);api.dispose();assert.equal(api.diagnostics().visibleBeams,0);assert.ok(api.getLights().every(l=>!l.visible&&!l.shadow.autoUpdate));});
